Float logo wrapper for better display of longer status page titles
louislam/uptime-kuma pull request #1152
Opened 2022-01-09 10:26 UTC by jamesmacwhite

# Description

On smaller viewports the status page logo and title display can better optimised, by having the logo wrapper as float, so the status page title is more neatly displayed. Essentially not trying to vertically centre the title with the logo as viewport has less space.

Currently without floating:

![image](https://user-images.githubusercontent.com/8067792/148678258-1b1a89b2-cdaa-4bfa-b592-c8546d7452f3.png)

When applying a float:

![image](https://user-images.githubusercontent.com/8067792/148678348-973fea90-3817-46cb-810c-aa92707b83ae.png)

## Type of change

- User Interface

## Checklist

- [X ] My code follows the style guidelines of this project
- [X] I ran ESLint and other linters for modified files
- [X ] I have performed a self-review of my own code and test it
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings
- [] My code needed automated testing. I have added them (this is optional task)
-

2022-01-10 14:25 UTC, Saibamen requested changes

2022-01-10 14:25 UTC, Saibamen commented on src/assets/app.scss
> +@media (max-width: 550px) {
Double enter
```suggestion
@media (max-width: 550px) {
```

2022-01-10 14:27 UTC, jamesmacwhite commented on src/assets/app.scss
> +@media (max-width: 550px) {
Thanks, forced pushed and fixed.

2022-01-19 12:01 UTC, jamesmacwhite commented
@Saibamen Is this OK to be merged?

2022-01-19 14:12 UTC, Saibamen approved these changes

2022-01-19 14:12 UTC, Saibamen commented
OK

2022-03-15 04:17 UTC, louislam commented
For single line, it is no longer aligned to the middle.

![image](https://user-images.githubusercontent.com/1336778/158305246-25f21368-6c5a-4c2d-8f4d-80be59ddad77.png)

2022-03-17 09:12 UTC, louislam commented
I fixed it by using flexbox. Thanks for raising the issue.
https://github.com/louislam/uptime-kuma/pull/863/commits/c0c641998093f0690fd0b83206e73f2568993fd2

![image](https://user-images.githubusercontent.com/1336778/158775509-bff7c705-e406-4d99-b111-6e9c9a53f32d.png)

2022-03-17 09:12 UTC, closed without merging