Implement Public Dashboard
louislam/uptime-kuma pull request #124
Opened 2021-07-30 07:02 UTC by chakflying

Don't know if anyone has worked on this yet, but here are my thoughts on the public dashboard feature:

- [ ] [Front-end] Break out separate Login page, add relevant navigation elements
- [ ] [Server] Change WebSocket API such that on Edit-related functions require Login
- [ ] [Front-end] Hide Edit-related UI elements if not Logged in

Optional:

- [ ] [Server] Add column `private` to table `monitor`, indicate monitors that will only be shown if logged in
- [ ] [Server] Change WebSocket API to return only non-private monitors if not logged in

2021-07-30 07:30 UTC, louislam commented
For my experience, because WebSocket client keeps connected to the server, the server cannot handle so many connections. So maybe make another "Status Page" for public is better to go. 

Like this, but without realtime data.
https://status.uptimerobot.com/

2021-07-31 15:21 UTC, Spiritreader commented
> For my experience, because WebSocket client keeps connected to the server, the server cannot handle so many connections. So maybe make another "Status Page" for public is better to go.
> 
> Like this, but without realtime data.
> https://status.uptimerobot.com/

While I understand the technical reasons behind it, having real-time data as a public status page is sadly the feature that all free/open source uptime monitors (except statping) lack.
It's still something many (including myself) people are looking for in a deployed status page.

Is it maybe possible to make it "semi-realtime" by statically requesting the last `x` pings from the database via a normal route?

Yes, people would be able to reload the page to see if something is up or down, but it would greatly decrease the number of open connections.

2021-07-31 16:08 UTC, louislam commented
> Is it maybe possible to make it "semi-realtime" by statically requesting the last `x` pings from the database via a normal route?

That is my thoughts too. The status page could be still made by Vue but without WebSocket, which keeps polling the result maybe every 5mins via REST API, and the result is cached every 5mins too.

Anyway, will do stress test later, see how much it can handles.

@chakflying I would prefer that this task let it to me first, since I would like to define the whole frame first. What do you think?

Thank you all.

2021-07-31 17:33 UTC, chakflying commented
I agree with having an HTTP API too, since someone else requested it. I'm just slightly concerned with the added complexity if we want the same front-end to handle both WebSocket and HTTP. The alternative I was thinking would be to set the front-end to only periodically connect the websocket on a timer, essentially turning it into polling. We could even tell the client to poll less often if under heavy load.

But I'm okay with not working on this further until we have a clear direction.

2021-09-06 11:55 UTC, pegaltier commented
Very good idea to have a public status page.

2021-09-11 08:32 UTC, Saibamen requested changes

2021-09-11 08:32 UTC, Saibamen commented on src/mixins/socket.js
> +const noSocketIOPage = [
This is array, so IMO this should be `noSocketIOPages`

2021-09-11 08:32 UTC, Saibamen commented on src/pages/StatusPage.vue
> +            console.log("here");
```suggestion
```

2021-09-11 08:33 UTC, Saibamen commented on src/pages/StatusPage.vue
> +            console.log("here");
```suggestion
        edit() {
```

2021-09-13 06:23 UTC, chakflying commented
If we are going the direction of a public HTTP api, I recommend splitting that part into a separate file `api.js`, then use it in the express server as a route handler.

2021-09-15 06:52 UTC, louislam commented
Still working on it.

Planning to support these features in 1.7.0:

- Theme (Dark / Light)
- Change Logo
- Change Title / Description
- Create incident announcements
- Sortable monitor list and group

<table>
<tr>
<th>Edit Mode</th>
<th>Public View</th>
</tr>
<tr>
<td>
<img src="https://user-images.githubusercontent.com/1336778/133384042-4fd75ba2-e561-4412-8e25-6687bd2f1739.png" />
</td>
<td>
<img src="https://user-images.githubusercontent.com/1336778/133384019-962e1120-6c3a-481f-9d07-d7df765e9ba4.png" />
</td>
</tr>
</table>

2021-09-16 19:07 UTC, Ponkhy commented
How about adding notifications for the incident announcements? 
Like, when you open or close one it'll send a notification with all the informations.

2021-09-16 19:17 UTC, louislam commented
> How about adding notifications for the incident announcements?
> Like, when you open or close one it'll send a notification with all the informations.

Good idea, public users could subscribe to follow the incident update.

2021-09-16 19:20 UTC, Ponkhy commented
Also another idea, how about a RSS Feed for it?

2021-09-19 16:46 UTC, louislam commented
> RSS Feed

I think people rarely use it nowadays, as modern browsers no longer support RSS and Google Reader is closed.

2021-09-21 18:48 UTC, nogweii commented
> I think people rarely use it nowadays, as modern browsers no longer support RSS and Google Reader is closed.

I use it a lot; there is a huge community of people using services like [Newsblur](https://newsblur.com/), [Feedly](https://feedly.com/), and [Inoreader](https://www.inoreader.com/). It's definitely the case that they aren't as huge as Google, but last I checked it's still millions of users across these and other similar services.

If XML is not your preference, there is a standard comparable to RSS but using JSON, [JSON Feed](https://www.jsonfeed.org/). Most feed readers have supported it for years.

2021-09-23 06:26 UTC, louislam commented
Almost finish. 

My preview: https://status.louislam.net/status-page

2021-09-23 07:24 UTC, TriForMine commented
I don't really know if this is good to have, but it would be nice.
Like when you click on a specific service, you get a graph(like the one available in the admin part) with the ping history ect. Maybe that could be disabled in the settings.
Just like the info expends with more details about the service.

Also, thanks for that amazing works it already looks amazing!

2021-09-23 08:54 UTC, merged