New incident system
louislam/uptime-kuma pull request #1253
Opened 2022-02-02 12:53 UTC by karelkryda

# Description

This commit includes a new incident creation and management system:
  - Removed the ability to create incidents through the status page
  - Added the ability to create incidents (publish updates, close and reopen incidents) via the dashboard
  - Added the ability to manually force a status override on the status page when creating an incident
  - Added a list of all current incidents above the overall status
  - Added incident history under the list of monitors (on the status page) (last 5 incidents)
  - Added history of all incidents broken down by year and month
  - Added the ability to view incident information from the status page (including the incident timeline)

## Type of change

Please delete any options that are not relevant.

- User interface (UI)
- New feature (non-breaking change which adds functionality)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I ran ESLint and other linters for modified files
- [x] I have performed a self-review of my own code and tested it
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] My code needed automated testing. I have added them (this is optional task)

## Screenshots (if any)

![image](https://user-images.githubusercontent.com/59953812/152156775-352482fb-1fc4-49a6-982f-a840e7ae573c.png)
![image](https://user-images.githubusercontent.com/59953812/152157172-0f1be4c2-ba54-40e8-8f34-4fff1d8138e5.png)
![image](https://user-images.githubusercontent.com/59953812/152157199-f2b7b432-af2b-458c-a62b-788aa3c18839.png)
![image](https://user-images.githubusercontent.com/59953812/152157129-a72a5f1c-6de3-4c56-8fd0-d86e4ef8113a.png)
![image](https://user-images.githubusercontent.com/59953812/152156960-0572351f-e041-46d5-9124-606ef27d432c.png)
![image](https://user-images.githubusercontent.com/59953812/152157015-c86ca827-2a9f-4a42-a3af-97e013d64ec4.png)
![image](https://user-images.githubusercontent.com/59953812/152156911-e0ce2347-d5e4-4c98-80b5-593779585254.png)

2022-02-03 03:14 UTC, Jeve-Stobs commented
This looks amazing. Just tested and if this can get approved for the next minor update, it will really improve the current status page. What a great addition!

2022-02-03 07:00 UTC, karelkryda commented
@Jeve-Stobs thank you 😊

2022-02-05 20:44 UTC, yun00001 commented
Will like this to be added into next update! this is so good!

2022-02-08 17:27 UTC, mathiskir commented
Wow! That would be incredibly useful!

2022-02-15 11:45 UTC, MedPlexNi commented
Is there any update? 👀
The function would be for us the direct switch to UptimeKuma, as it would be really essential and we love UptimeKuma :3

2022-02-15 19:11 UTC, trdwll commented
Please. lol. This would be amazing.

2022-02-18 00:26 UTC, notdatabase commented
YES please. This would finally be why at work I can switch away from Statuspage/Cachet.

2022-02-19 10:25 UTC, mathiskir commented
Hey,
I just tested it and I have some ideas for improvements:
- different colors for status of incidents (started, update, resolved)
![image](https://user-images.githubusercontent.com/65130981/154796718-8d50ee2a-848d-445d-9f4b-8e704bff8193.png)
- mark affected monitors somehow, so that it's clearer for end users (with an icon??)
![image](https://user-images.githubusercontent.com/65130981/154796764-2f6dab10-c944-4d90-8d82-49c75a982619.png)
But besides that, it's great!

2022-04-03 17:44 UTC, finnie2006 commented
I am really waiting for this, this is a game changer

2022-04-03 17:45 UTC, finnie2006 commented
I am really waiting for this, this is a game changer, and this feature will also be nice for companies etc @louislam

2022-04-03 18:21 UTC, finnie2006 commented
but it is actually outdated already and pretty far off the master branch

2022-04-03 18:50 UTC, karelkryda commented
> but it is actually outdated already and pretty far off the master branch

It is true that with each new commit to the `master` branch, this pull request moves away from the current code, but I hope it will be merged soon.

2022-04-03 19:15 UTC, finnie2006 commented
i think you should try to keep it a bit up to date, i dont think he will merge it if its outdated

2022-04-03 23:31 UTC, Saibamen commented on src/components/MonitorList.vue
> +                if (i1.resolved !== i2.resolved) {
```suggestion
            result.sort((i1, i2) => {
                if (i1.resolved !== i2.resolved) {
```

2022-04-03 23:31 UTC, Saibamen commented on src/pages/EditIncident.vue
> +        pageName() {
```suggestion
    computed: {
        pageName() {
```

2022-04-03 23:31 UTC, Saibamen commented on src/pages/EditIncident.vue
> +        "$route.fullPath"() {
```suggestion
    watch: {
        "$route.fullPath"() {
```

2022-04-03 23:31 UTC, Saibamen commented on src/pages/IncidentsPage.vue
> +        // Set Theme
```suggestion
    watch: {
        // Set Theme
```

2022-04-04 16:45 UTC, karelkryda commented
> i think you should try to keep it a bit up to date, i dont think he will merge it if its outdated

Unfortunately, I do not currently have the opportunity to do this and update this pull request with the master branch.

I'm busy right now, and this action requires a lot of code comparison and additional testing to see if everything still works.

2022-04-04 17:49 UTC, karelkryda commented
I would love for @louislam to resolve the issues before merge this pull request.

I've tried to resolve conflicts now, but it's not something I do every day and I don't know much about it. In the end, this created absolute chaos, and I doubt it would ever work again 😁.

Maybe it will be resolved soon and it will be merged.

Sorry 😔

2022-04-04 18:08 UTC, louislam commented
> I would love for @louislam to resolve the issues before merge this pull request.
> 
> I've tried to resolve conflicts now, but it's not something I do every day and I don't know much about it. In the end, this created absolute chaos, and I doubt it would ever work again 😁.
> 
> Maybe it will be resolved soon and it will be merged.
> 
> Sorry 😔

Thanks, to save your time, I suggest that it could be resolved later, because I think pull requests like #1083 and #1415 will be merged before this pr.

2022-04-04 18:13 UTC, karelkryda commented
> > I would love for @louislam to resolve the issues before merge this pull request.
> > I've tried to resolve conflicts now, but it's not something I do every day and I don't know much about it. In the end, this created absolute chaos, and I doubt it would ever work again 😁.
> > Maybe it will be resolved soon and it will be merged.
> > Sorry 😔
> 
> Thanks, to save your time, I suggest that it could be resolved later, because I think pull requests like #1083 and #1415 will be merged before this pr.

I understand. I will be happy if you would take care of resolving the conflicts or help me with them, because I really don't know how to do it 🤦🏻‍♂️.

2022-04-04 18:18 UTC, louislam commented
Would try to help later. Might need some works, as I remember this pr is created before multiple status pages support.

2022-04-04 18:24 UTC, mathiskir commented
> * different colors for status of incidents (started, update, resolved)
> * mark affected monitors by a maintenance somehow, so that it's clearer for end users (with an icon??)

I think these two things would be really nice to have and don't require much of work.
Could you maybe implement it before merging it, or what do you think about these two features?

2022-04-04 18:30 UTC, karelkryda commented
> mark affected monitors by a maintenance somehow, so that it's clearer for end users (with an icon??)

I planned to do this, but I forgot 😁

> different colors for status of incidents (started, update, resolved)

Do you mean the colors on the timeline? It should theoretically be possible there.

Incidents are color-coded according to priority (type).

2022-04-04 18:50 UTC, mathiskir commented
> Do you mean the colors on the timeline? It should theoretically be possible there.
![image](https://user-images.githubusercontent.com/65130981/154796718-8d50ee2a-848d-445d-9f4b-8e704bff8193.png)
yes on the page you can see at the screenshot above

2022-04-11 10:09 UTC, LukeD1994 commented
Just wanted to drop my support for this PR, it would be an absolute blessing to have.

I tested merging this manually myself, with build 1.14.0-beta1. I did it in a very hacky way, it doesn't fully function because I haven't (yet) gone through and edited the PR code to make it work with the multiple status pages features (I don't need multiple pages), all in all a great addition. Of all the PR's, this is one I would very much like to see integrated properly. :)

2022-04-19 03:13 UTC, gaby commented
@karelkryda Could you rebase this with master? There's a lot of conflicts right now

2022-04-19 08:07 UTC, karelkryda commented
> @karelkryda Could you rebase this with master? There's a lot of conflicts right now

We talked about it, look up a little bit.

2022-04-20 03:53 UTC, gaby commented
@karelkryda Now worries, I didn't read the whole thread. I was trying to merge this on my fork and failed miserably. There's a massive conflict in StatusPage.vue because of https://github.com/louislam/uptime-kuma/pull/1083 and https://github.com/louislam/uptime-kuma/pull/1415

2022-04-20 07:36 UTC, karelkryda commented
> @karelkryda No worries, I didn't read the whole thread. I was trying to merge this on my fork and failed miserably. There's a massive conflict in StatusPage.vue because of https://github.com/louislam/uptime-kuma/pull/1083 and https://github.com/louislam/uptime-kuma/pull/1415

Yeah, that's why I'll need help before merge 😕

2022-04-23 17:58 UTC, mathiskir commented
@louislam could you maybe help @karelkryda with these massive merge conflicts so this can maybe be a thing in 1.16 or 1.17?
Or are there any big pull requests that aren't merged yet?

2022-04-23 19:18 UTC, Computroniks requested changes
Would it be possible for you to add JSDoc comments to all the methods you have added? I have added suggestions for some of them here but if you need a hand just let me know. (Related to #1499)

2022-04-23 19:18 UTC, Computroniks commented on src/pages/IncidentDetails.vue
> +        clear() {
```suggestion
        /** Clear messages */
        clear() {
```

2022-04-23 19:18 UTC, Computroniks commented on src/pages/IncidentPage.vue
> +        logoURL() {
```suggestion
        /**
         * Get URL of logo
         * @returns {string}
         */
        logoURL() {
```

2022-04-23 19:18 UTC, Computroniks commented on src/pages/IncidentPage.vue
> +        isPublished() {
```suggestion
        /**
         * Has the status page been published?
         * @returns {boolean}
         */
        isPublished() {
```

2022-04-23 19:18 UTC, Computroniks commented on src/pages/IncidentPage.vue
> +        theme() {
```suggestion
        /**
         * Get page theme
         * @returns {string}
         */
        theme() {
```

2022-04-23 19:18 UTC, Computroniks commented on src/pages/IncidentsPage.vue
> +        logoURL() {
```suggestion
        /**
         * Get URL of logo
         * @returns {string}
         */
        logoURL() {
```

2022-04-23 19:18 UTC, Computroniks commented on src/pages/IncidentsPage.vue
> +        isPublished() {
```suggestion
        /**
         * Is the status page published?
         * @returns {boolean}
         */
        isPublished() {
```

2022-04-23 19:18 UTC, Computroniks commented on src/pages/IncidentsPage.vue
> +        theme() {
```suggestion
        /**
         * Get current theme
         * @returns {string}
         */
        theme() {
```

2022-04-23 19:18 UTC, Computroniks commented on src/util.js
> +function getIncidentRelativeURL(id) {
```suggestion
/**
 * Get relative URL of incident
 * @param {number} id ID of incident
 * @returns {string}
 */
function getIncidentRelativeURL(id) {
```

2022-04-23 19:37 UTC, louislam commented
> @louislam could you maybe help @karelkryda with these massive merge conflicts so this can maybe be a thing in 1.16 or 1.17? Or are there any big pull requests that aren't merged yet?

I just have a quick look of source code. I am afraid that it won't be merged shortly.

1. As this pr created before multiple status pages, a lot of logic and ui/ux of this pr may need to be redesigned. For example, I think "create incident" button and incident management should be moved back to status page instead of dashboard, which won't be so easy.

2. I believe the database schema/relations need to be changed too.

3. There are some breaking changes like changing the url from `/dashbaord/:id` to `/dashboard/monitor/:id`, which I maybe cannot accept that, because bookmarked monitor urls will become 404.

4. I think all existing function names or route names should not be modified.

2022-04-23 19:56 UTC, mathiskir commented
So @karelkryda has **a lot** of work to do

2022-04-24 11:56 UTC, karelkryda commented
> > @louislam could you maybe help @karelkryda with these massive merge conflicts so this can maybe be a thing in 1.16 or 1.17? Or are there any big pull requests that aren't merged yet?
> 
> I just have a quick look of source code. I am afraid that it won't be merged shortly.
> 
> 1. As this pr created before multiple status pages, a lot of logic and ui/ux of this pr may need to be redesigned. For example, I think "create incident" button and incident management should be moved back to status page instead of dashboard, which won't be so easy.
> 2. I believe the database schema/relations need to be changed too.
> 3. There are some breaking changes like changing the url from `/dashbaord/:id` to `/dashboard/monitor/:id`, which I maybe cannot accept that, because bookmarked monitor urls will become 404.
> 4. I think all existing function names or route names should not be modified.

1. Personally, I think it's better for incidents to be created directly in the dashboard. It's definitely more convenient (at least in my opinion). Theoretically, it would not be a problem to add the option to select on which status pages the incident is displayed (or to display it on all status pages on which the affected monitor is displayed).
2. If we decided to choose the option of selecting the status pages on which the incident will appear, it would be necessary.
3. Regarding this step, my goal was to make the URL address make sense. With the ability to schedule maintenance, create incidents and monitors in the future, it would make more sense for the URL to match. Theoretically, it would be possible to add a redirect condition to the router, right? That is, `/dashboard/:id` would be redirected to `/dashboard/monitor/:id`. Again, it depends on the agreement....

2022-04-24 12:00 UTC, karelkryda commented
> So @karelkryda has **a lot** of work to do

Unfortunately, it seems that it will be necessary to start from scratch, which makes me a little sorry and annoying at the same time.

I'm currently taking my final exams at school and therefore I can't work on this PR. When I'm done after the exams, I'd look at it and try to redo this PR.

2022-04-24 14:34 UTC, louislam commented
I will also come back to this pr later, I am planning to merge older big pull requests such as #1119 or smaller pull requests first.

2022-05-04 08:50 UTC, finnie2006 commented
This pr really should be a standard feature of uptime monitroring software

2022-05-18 10:09 UTC, karelkryda commented
@louislam Should I prepare this PR for milestone 1.17.0?

2022-05-18 11:47 UTC, louislam commented
I will go for the maintenance pr first, it should be in 1.18.0.

2022-05-18 11:54 UTC, karelkryda commented
> I will go for the maintenance pr first, it should be in 1.18.0.

Okay, please let me know and I'll prepare the PR. 
It is useless to do this now that there will be a lot of commits up to version 1.18.0.

2022-07-04 21:43 UTC, Nuckerr commented
So any updates for this?

2022-08-03 08:57 UTC, heiko-ma commented
Will this PR be included in 1.18.0? This is the only missing feature which prevents us from migrating from cachet to uptime kuma.

2022-08-03 09:02 UTC, karelkryda commented
> Will this PR be included in 1.18.0? This is the only missing feature which prevents us from migrating from cachet to uptime kuma.

that's a good question. In fact, my next (maintenance planning) PR still hasn't been completed and has been postponed.

2022-08-08 11:25 UTC, reigio commented
This incident system is most important feature missing that keeps me form using Uptime-kuma. Any organisation interested in their systems uptime is in need for good incident handling. Please consider moving it up in the new features list.
Maintenance planning would be nice too.

2022-09-05 08:07 UTC, finnie2006 commented
This takes way too long, this is just a mandatory feature, have now switched to other software because without this feature this cannot be deployed

2022-09-05 18:09 UTC, gaby commented
@finnie2006 What other software have you found? I have debated forking this project and merging all these PR's in a fork

2022-09-05 18:23 UTC, MarcHagen commented
@finnie2006 @gaby and all others.

Please let this PR just be.
Don't comment with (why, when and how) questions. It will not speedup the process and clutters the discussion for this PR.

Thank you all for understanding.

2022-12-06 20:31 UTC, sgeneralgrievous commented
has this been added yet?

2022-12-08 09:18 UTC, george-martinec commented
Please add

2023-01-31 07:37 UTC, louislam commented
I merged some code in my local branch and tested it. I just realized that the relation between `status_page` and `incident` was dropped, and it is now becoming the relation between `monitor` and `incident`.

And I think `incident` belonging to `status_page` is much more straightforward, because sometimes people just want to type something in a status page. In new design, if they want to do the same thing, they need to find a monitor that is belonging to the status page in the dropdown list first, which maybe a bit strange. So I prefer a many-to-many or one-to-many (current) relation between `status_page` and `incident`.

Plus similar to the maintenance pr, there are some UI changes may need to be reworked and improved.

So I pulled it out from 1.20.0 milestone. I think the database design have to be discussed first.

2023-03-23 04:18 UTC, icecoffee531 commented
I have an idea about the new incident system: Can the impact time of failure events recorded on the status page be reflected in the monitoring? For example, if a fault occurs for five minutes, and the corresponding event is recorded, should it also be a fault state during the five minutes of monitoring?

2023-03-23 04:21 UTC, icecoffee531 commented
I have an idea about the new incident system: 

Could the impact time of `incident` recorded on the `statuspage` be reflected in the monitoring? 

For example, if a fault occurs for 5 minutes, and the corresponding `incident` is recorded, should it also be a fault state during the 5 minutes of monitoring?

2023-04-01 14:28 UTC, NOXITB commented
Waiting on this still come on we need this

2023-04-09 13:24 UTC, ShadowGaming100 commented
Since there is already a pull request about incident. If is possible can you add my feature #2933

2023-05-12 10:02 UTC, vcantrell commented
Desperately waiting for this feature as well... It's literally the deciding feature I need for my status page; Still using Kuma, but would REALLY love if this feature could be added so I could track previous incidents and their updates/resolutions....

2023-05-15 14:37 UTC, thexperiments commented
+1 any chance to have this in soonish? Also deciding factor for us to go with kuma

2023-05-18 05:01 UTC, Thakurvaibhav commented
Can we please get this in soon?

2023-05-20 10:58 UTC, CommanderStorm commented
@thexperiments @Thakurvaibhav @vcantrell @NOXITB @george-martinec @sgeneralgrievous 
Please refrain from posting `+1` / requests for update-things on PRs, as this makes reviewing it even harder.
[We use 👍🏻 on PRs to prioritise work](https://github.com/louislam/uptime-kuma/pulls?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

2023-07-03 14:19 UTC, CommanderStorm commented
@karelkryda 
Could you separate the `Fixes #... #...` into separate lines? (This way Github links this as a PR that closes them)
Could you also add `Fixes #2926`?

2023-10-07 12:53 UTC, omi-the-sorcerer commented
I would like to be able to continue with this task. I have @karelkryda's incident system adapted for the master, and I could proceed with the development of the incident system until completion. However, I don't know how to organize myself with Git. Could someone help me?

2023-10-07 12:55 UTC, SachsenspieltCoding commented
> I would like to be able to continue with this task. I have @karelkryda's incident system adapted for the master, and I could proceed with the development of the incident system until completion. However, I don't know how to organize myself with Git. Could someone help me?

@omi-the-sorcerer Do you have a specific problem or do you need just general help?

2023-10-07 13:07 UTC, omi-the-sorcerer commented
well..
The thing is, I've never used Git for collaboration as I would like to do with this project to add a feature that would be really interesting. I forked the repository to my account and created a new branch from master with an empty commit, as indicated in CONTRIBUTING.md.

I have all the code locally, more or less prepared to improve the database relationships, as discussed in this PR, and to adapt the incident system by monitoring so that incidents have an impact on it, among other things. But I don't know how to proceed to start uploading code, discussions to the PR, or other requirements so that we can include it in an upcoming milestone like 2.x perhaps."

2023-10-07 13:18 UTC, SachsenspieltCoding commented
I have to say, I don't know how the maintainers prefer it, but IMO I think it would be a good first option to just push all your changes into your fork. That way, we can test, review and discuss them before opening a new PR, which might result in two PRs that don't get merged.

If you need any further help with Git or GitHub, feel free to contact me on Discord @sachsenspielt if you have one.

2023-11-23 16:13 UTC, designermonkey commented
Hi @louislam, I'd like to suggest that there should be some sponsorship to implement this feature. I know the project is open source and relies on your goodwill and time to maintain, but this feature would make this project one of the best platforms available to monitor uptime and incidents.

I would happily contribute if sponsorship were available per feature, like a bounty. I wonder what others think.

2023-11-23 16:17 UTC, designermonkey commented
@omi-the-sorcerer the best way to manage the forks and changes is to make sure your changes are on github in your fork, then open a PR to the relevant branch on @karelkryda 's fork as this PR originated there, and it should automatically update this fork if/when @karelkryda merges those changes.

2023-11-23 16:23 UTC, karelkryda commented
If there is someone who would merge all the changes from the `main` branch and ensure this PR up-to-date again, I would be happy. I no longer track changes made to the `main` branch the same way I did before.
To be honest, I wasn't even motivated to do it due to the fact that there was no interest in merging this PR.

2023-11-23 16:26 UTC, gaby commented
> If there is someone who would merge all the changes from the `main` branch and ensure this PR up-to-date again, I would be happy. I no longer track changes made to the `main` branch the same way I did before. To be honest, I wasn't even motivated to do it due to the fact that there was no interest in merging this PR.

^This, same thing happend to a lot of other great PR's. The whole project is being managed by 1 person who doesnt allow others to help him with merges, etc. Having over +800 issues, and +90 open PR's for 1 maintainer is too much.

2023-11-23 16:40 UTC, karelkryda commented
I completely understand that this is too much for one person. Moreover, if he has a full-time job. The reason why I don't have time to devote to this as much as before is also my full-time job.

To tell you the truth, I think that if we want to achieve the goal effectively, we shouldn't do it in such a way that someone comes and puts their time into PR and gives up after some time of effort. Rather, we should try to get in touch with Louislam and work closely together to ensure that the merge occurs within a few days of updating this PR at most. Otherwise, PR will become obsolete again and it will turn out the same.

And now I'm not just talking about this PR. Of course, more people maintaining this project would be a better option than just one, but I understand his possible concerns about his work and his desire to avoid potential problems.

2023-11-23 17:36 UTC, SachsenspieltCoding commented
I have no problem helping to merge and bring this feature to life, but I agree with @karelkryda
Without support from Louislam it is more or less hopeless. He is currently trying to build a second OSS project ([dockage](https://github.com/louislam/dockge)). I mean, it's his decision and I won't criticise him too much, but is it a good idea when also maintaining such a big project like uptime-kuma?

2023-11-23 17:46 UTC, karelkryda commented
I understand that he is trying new things. I did it too, and I enjoyed it. 

However, I can't help feeling that it would be the right approach to create Uptime Kuma organization and build a community around it to take care of the project. It's problematic, but Uptime Kuma is a big and I would say successful project with a lot of users capable of developing and maintaining software. At the moment, it seems to me to be a wasted potential.

It's a big step, but Louislam would have his hands free to focus on his new projects. Now he's basically trying to do several things at once, and I can say from experience that it usually doesn't work, unfortunately.

2023-11-23 18:16 UTC, louislam commented
@karelkryda Thanks for understanding. I still remember you did a great job of the maintenance feature. But sorry for holding this pr for so long due to my higher expectation.

@gaby I also remember you helped a lots initially of this project, want to say thank you again.

But sometimes I really have my own thoughts, I have my own project styles. I opened source this project, didn't mean I have to accept everything changes without asking me. And sometimes I just don't want to argue so much. 

So last year, I have updated the contribution rules, any new features should ask me first, I think it is fair. 

> Discussion required
    - Large pull requests
    - New features

https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md#can-i-create-a-pull-request-for-uptime-kuma


Also to be fair, contributors like @chakflying @CommanderStorm @Computroniks are always helping to manage issues and review pull requests. Also want to say thanks here, they saved my time a lot.


And `854` is the number of merged pull requests without my pull requests:

<img src="https://github.com/louislam/uptime-kuma/assets/1336778/bc5cbbf9-e04c-42be-8ab5-9ef727031edb" width="400">



@designermonkey
I am not good at finding sponsorships unfortunately.
Actually I did review this pr, but as mentioned in https://github.com/louislam/uptime-kuma/pull/1253#issuecomment-1409899850, I am not satisfied with the database schema and some UX/UI. If anyone want to rework or continue this pr, feel free to let me know, so we can have a discussion, it could be in the 2.2.0 milestone.

2023-11-23 18:39 UTC, Zaid-maker commented
DAMN! 2 years this PR is open 🤯

2023-11-25 18:29 UTC, paranic commented
@louislam yes but i believe that a incident history feature would be great, not as complicated and feature rich as this one a more simpler one that does the job would be great. just a place to explain some historical incidents when required.

this would complete the uptime kuma mission as a project.

2023-11-25 23:48 UTC, CommanderStorm commented
@paranic 

Please refer to the comment above:

> If anyone wants to rework or continue this pr, feel free to let me know, so we can have a discussion, it could be in the 2.2.0 milestone.

Here is our contribution guide: https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md

2023-12-04 00:12 UTC, CommanderStorm commented
@shivaneshlal our plans for what PRs/issues get merged in what release can be looked at under https://github.com/louislam/uptime-kuma/milestones if that is what you mean.

2024-02-02 15:56 UTC, tteddy623 commented
> DAMN! 2 years this PR is open 🤯

I know this is not a discussion forum but I cant help myself. The lack of this simple feature (that we all know EVERYONE is waiting for) is mindblowing. Its like an emo garage band fighting over creative control. The PR of this uptime is pretty bad.

2024-02-02 16:15 UTC, apio-sys commented
@tteddy623 like you see this is not a discussion forum for some commercial software. It's FOSS, hence all can contribute but not *require* any changes to be done or features to be implemented. I very much like the initial feature proposal as well but as you can see in the thread there wasn't a real discussion before (rather just dumped a PR) and only weeks after the PR, the code is too far off the main branch which follows already its roadmap. Hence, if you like it, you should help it get back on the rails rather than expecting someone else to do that (or if you do, then just be patient without asking/complaining).

2024-02-02 17:42 UTC, CommanderStorm commented
Honesty, I think keeping this open is not helping the discussion
Our previous comments still stands:

> If anyone wants to rework or continue this PR, feel free to let us know, so we can have a discussion, it could be in the 2.2/2.3 milestone.
> 
> Here is our contribution guide: https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md

2024-02-02 17:42 UTC, closed without merging

2024-02-02 20:08 UTC, karelkryda commented
@CommanderStorm I'm not sure if closing this PR will help anything. Maybe it would be better to find someone to help bring this PR back to a compatible state. Quite likely it would have happened in the new PR, but... 

Wouldn't it be better to keep an eye on this PR with all the discussion and everything around it?

2024-02-02 23:19 UTC, CommanderStorm commented
I am going to split my answer into multiple parts to keep this legable.

- > I'm not sure if closing this PR will help anything
  
  The rationale why I closed it is the same as in https://github.com/louislam/uptime-kuma/pull/1236#issuecomment-1924740307 and has to do with expectaion management.
Given your comment[^1], I consider this PR abandoned and without addressing the remaining issues this won't be merged.
  If something has changed since then, we can reopen this PR, but otherwise I think that keeping this closed is better.
  
  <details><summary>Here is the relevant part of the relevant part of https://opensource.guide/best-practices/</summary>
  <p>
  
  > Don’t leave an unwanted contribution open because you feel guilty or want to be nice. Over time, your unanswered issues and PRs will make working on your project feel that much more stressful and intimidating.
  > 
  > It’s better to immediately close the contributions you know you don’t want to accept. If your project already suffers from a large backlog, @ steveklabnik has suggestions for [how to triage issues efficiently](https://words.steveklabnik.com/how-to-be-an-open-source-gardener).
  > 
  > Secondly, ignoring contributions sends a negative signal to your community. Contributing to a project can be intimidating, especially if it’s someone’s first time. Even if you don’t accept their contribution, acknowledge the person behind it and thank them for their interest. It’s a big compliment!
  > 
  > If you don’t want to accept a contribution:
  > 
  > - **Thank them** for their contribution
  > - **Explain why** it doesn’t fit into the scope of the project, and offer clear suggestions for improvement, if you’re able. Be kind, but firm.
  > - **Link to relevant documentation**, if you have it. If you notice repeated requests for things you don’t want to accept, add them into your documentation to avoid repeating yourself.
  > - **Close** the request
  
  </p>
  </details> 
  
  I should have communicated better and f.ex. thanked you for the work you did. Sorry about that.
- > Maybe it would be better to find someone to help bring this PR back to a compatible state
  
  Finding people chip in is the goal of the mentioning of the contribution guide. I don't know how effective that is or how we can be more effective.
  ⇒ If somebody wants to help us out on this one, this help would very appreciated
  
  Something that you might have noticed is that there has been a small shift in how Uptime Kuma is maintained. In December @chakflying and I have has joined as a junior maintainers. Currently we split the roles of bugfixing/features/triage/refactoring/moderation pretty evenly.[^2]
  
  If you/somebody has feedback for us (the maintainers) where we are failing/can improve, we are always happy to listen.
  
  <details><summary>Here is the relevant part of the relevant part of <a href="https://opensource.guide/best-practices/"><code>opensource.guide/best-practices</code></a></summary>
  <p>
  
  > If you’re looking for others to pitch in, start by asking around.
  > 
  > One way to gain new contributors is to explicitly [label issues that are simple enough for beginners to tackle](https://help.github.com/en/articles/helping-new-contributors-find-your-project-with-labels). GitHub will then surface these issues in various places on the platform, increasing their visibility.
  > 
  > When you see new contributors making repeated contributions, recognize their work by offering more responsibility. Document how others can grow into leadership roles if they wish.
  > 
  > Encouraging others to [share ownership of the project](https://opensource.guide/building-community/#share-ownership-of-your-project) can greatly reduce your own workload, as @ lmccart discovered on her project, [p5.js](https://github.com/processing/p5.js).
  > 
  > > ’d been saying, “Yeah, anyone can be involved, you don’t have to have a lot of coding expertise […].” We had people sign up to come [to an event] and that’s when I was really wondering: is this true, what I’ve been saying? There are gonna be 40 people who show up, and it’s not like I can sit with each of them…But people came together, and it just sort of worked. As soon as one person got it, they could teach their neighbour.
  > > — @ lmccart, [“What Does “Open Source” Even Mean? p5.js Edition”](https://medium.com/@kenjagan/what-does-open-source-even-mean-p5-js-edition-98c02d354b39)
  > 
  > If you need to step away from your project, either on hiatus or permanently, there’s no shame in asking someone else to take over for you.
  > 
  > If other people are enthusiastic about its direction, give them commit access or formally hand over control to someone else. If someone forked your project and is actively maintaining it elsewhere, consider linking to the fork from your original project. It’s great that so many people want your project to live on!
  > 
  > @ progrium [found that](https://web.archive.org/web/20151204215958/https://progrium.com/blog/2015/12/04/leadership-guilt-and-pull-requests/) documenting the vision for his project, [Dokku](https://github.com/dokku/dokku), helped those goals live on even after he stepped away from the project:
  > 
  > I wrote a wiki page describing what I wanted and why I wanted it. For some reason it came as a surprise to me that the maintainers started moving the project in that direction! Did it happen exactly how I’d do it? Not always. But it still brought the project closer to what I wrote down.
  </p>
  </details> 
- > Quite likely it would have happened in the new PR, but... Wouldn't it be better to keep an eye on this PR with all the discussion and everything around it?
  
  I don't quite get this argument.
  Closing a PR does not equal deleting it.
  Clarification needed.



[^1]: See https://github.com/louislam/uptime-kuma/pull/1236#issuecomment-1787005830
      > Since I don't see interest in merging, it doesn't make sense for me to edit anything at the moment.
      > I don't have a problem with louislam modifying and merging this PR, but I don't have enough free time to do it at the moment.
[^2]:  This paragraph was added because of https://github.com/louislam/uptime-kuma/pull/1253#issuecomment-1824773839

2024-02-02 23:59 UTC, karelkryda commented
@CommanderStorm, I just thought that this PR has a better chance of success if it is open and therefore in front of people. I believe a lot of people will only look at open PRs.

I wish this PR was accepted, after all, I put a lot of work into it. However, I cannot force or influence anyone's decisions. If you feel that closing this PR is a better option, I can't contradict you.

I would like to thank everyone for the time and effort they have put into trying to merge this PR. I would also like to wish a happy future for this project, I believe it has a future. 

Thank you again and I wish you a pleasant rest of the day.

2024-02-03 04:55 UTC, tteddy623 commented
@apio-sys  ...oh didnt see that comming! C'mon. No, lets not overcomplicate this as if we're in a fortune 500. The manner in which the project was taken in principle is garbage. Focusing on a bunch of nonsense PRs.  My angst has nothing to do with coding its about managment of a project and its flexibility. But if louislam wants to hide behind his asthetics, fine. Many of the requests are common sense but you guys sit back and say, "well its too late now". Ya- becasue of poor project planning. This could have been a goldmine but...oh well.  And what do you think @karelkryda has been trying to do? Someone develops and you say, "Its too late".  Someone complains and you say, "then develop!". Bunch of highschool nonsense.

2024-02-03 07:26 UTC, louislam commented
For @tteddy623 

Please be friendly, you are not the boss here. Your comment is totally not valid to us. This is not Google, not Microsoft, everyone here are basically volunteers who loved Uptime Kuma, we use our free time to maintain it.

I think I said several time here in this repo, again, I only enjoy coding, not arguing. If you think the progress is slow and bad, how about you hire all of us here as a full time programmers and hire a project manager to manage the timeline and requirements? No? Then please be quite and understand what is FOSS as @apio-sys said. 

For @CommanderStorm @karelkryda

Regardless of the best practice, I am kind of agree with @karelkryda.🤣 I personally may prefer to keep stale pull requests opening. But I also don't want to make anyone feel unhappy here, I hope there is a way to balance it.


For others:

Since the thread is too long, I think my last review is hidden now for most people: https://github.com/louislam/uptime-kuma/pull/1253#issuecomment-1409899850

Basically I think `incident` should belong to `status_page` rather than `monitor`, which is the main blocking reason. 

As I said previously, if anyone want to take over this pr, or you have opinions on the database design. Feel free to comment here. Other judging comments, asking for ETA are not welcome, thanks.

2024-02-03 09:06 UTC, karelkryda commented
Okay @louislam, let's say that I would try to redo the PR so that it would be up-to-date again and at the same time it would be possible to create an incident without the need to link it to the monitor, but only to the status page.

Should I do this on top of the current master version or on top of the planned version 2.0?

How do you imagine the right design? Should I allow an incident to be displayed on a specific status page(s) and select any monitors that are affected by the incident? Does this mean that an incident will be created primarily for the status page and not for the monitor?

Regarding the actual design, do we want to hide incidents in the menu as well as maintenences?

Do you have any major changes planned that would result in its immediate incompatibility after the PR overhaul?

Would it be possible on your part to guarantee, let's say, activity in this PR in the sense of, for example, responding to my questions so that I can still discuss the decision and you guide me in the right direction in which you want this PR to be?


Please let me know, I would like to resolve this to the satisfaction of all involved.

2024-03-05 17:06 UTC, tkbstudios reviewed
## What I did
I reviewed all 31 files, it took around a day.  
I started Uptime Kuma in a monitored network environment and I haven't seen anything about personal data pass through, so I think it's safe (at least that's what I think, you might say it's not).  

## What I think
People claim that a 4K+ PR isn't acceptable but it is.  
This man was probably hours maybe days behind his PC working on this amazing feature and deserves someone taking the time for reviewing.  
I know the chance that this gets merged due to all the new commits but this man deserves credits for his amazing code!  
This incident system is kinda crazy and deserved the merge.  
I know this won't merge but still deserved a review.  
I think I'll use this PR version for kuma.

2024-03-05 17:57 UTC, tkbstudios commented
> @tkbstudios
> 
> > ## What I did
> > I reviewed all 31 files, it took around a day. I started Uptime Kuma in a monitored network environment and I haven't seen anything about personal data pass through, so I think it's safe (at least that's what I think, you might say it's not).
> 
> thank you very much for your time, and I fully support your opinion, do you have an updated fork to test it with the latest version of uptime-kuma? or did you just used the PR for the installation?

I used the PR version, so it's pretty outdated and is not recommended for production :/  
It's still a great PR and I think it should be updated for the newer Uptime Kuma version :)

2024-04-12 15:32 UTC, ShadowGaming100 commented
a very system should be merged no matter what you have worked countless hours also who helped.