[BUGFIX] Fix for docker(-compose) to allow the app to be run as a regular user.
louislam/uptime-kuma pull request #1286
Opened 2022-02-09 15:19 UTC by justSem

# Description

Fixes #857 and #694 

Due to the calling of setpriv as an regular user and some weird env variable stuff which seemed set wrongly to me the application couldn't be launched in docker as a non-root user.
(And really, an application like this _shouldn't_ run as root as it simply doesn't need it)

The proposed fix properly sets the environment variables reflecting the actual UID and GID and asseses this before launching.

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Checklist

- [X] My code follows the style guidelines of this project
- [ N/A ] I ran ESLint and other linters for modified files
  - Not applicable. I modified a bash file ;)
- [X] I have performed a self-review of my own code and tested it
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings

## Screenshots (if any)

Please do not use any external image service. Instead, just paste in or drag and drop the image here, and it will be uploaded automatically.

2022-02-12 21:59 UTC, k3rnelpan1c-dev commented
While this is certainly one way to handle rootles container or containers that run as non root account due to CLI params (i.e. `--user 1001:1001`), would it not be a more standard way to let the container run as a non root user by default?

What I mean by that is that most of the entrypoint script could be made obsolete and to simply create a user+group during the container build and ensure that the `/data` dir gets creted and properly assigned.

> As I have to deal with this a lot at work some reference from a platform that enforces the container to run as non root unless you explicitly allow it otherwise: [OpenShift has a section in their docs on how to build a container so it supports arbitrary user ids](https://docs.openshift.com/container-platform/4.9/openshift_images/create-images.html#use-uid_create-images)

I know this works, since I ended up building a custom image that uses the recomendation from the docs as well as what Nginx uses for their unpribileged container to test `uptime-kuma` in an unprivileged enforcing environment.
https://github.com/nginxinc/docker-nginx-unprivileged/blob/main/stable/debian/Dockerfile#L20-L21

However, the question remains if this would be the 'better' way or to keep the entrypoint script and use the fix proposed by this PR.

Either way, these are just my two cents to the matter that came up when I saw that you where faster than me to propose changes :slightly_smiling_face:

2022-02-12 23:26 UTC, k3rnelpan1c-dev commented
from what I can tell the scrip has nothing NodeJS specific.
It really just ensures that the `/data` dir exists and has its owner set 'properly' (with your fix it actually does that, b4 you would have had to specify `PUID` and `PUID`) and spawns of the NodeJS process as the same user the data dir now has as its owner.

At least that is what I could gather from it :)

Regardless, all I wanted to do is throw in the comment and open a discussion which way is the preferable one.

Either works since even if you where to create a user within the container build and run by default as that a user could still use the container runtime CLI (Docker, Podman, ...) to overwrite the user and group the container will run as would then lead to the NodeJS process to run as those ids.

There is only one instance where I am not 100% certain how it would react, if a user where to use a docker volume to mount on a pre-created `/data` dir (created at container build time and owned by the user created at build time) but setting a different UID and GID via the CLI or a thing such as Compose.
The likely 'solution' for that would be to set the `/data` dir at creation to 777.
(hope that made sense)

2022-02-13 01:02 UTC, k3rnelpan1c-dev commented
Thanks for testing my assumed edge case :sweat_smile: 
And yeah I assumed as much that it would run into this issue.
Setting the dir to 777 is NEVER a good idea so my apologies for bribing it up at all, was just throwing it out there for the only way to avoid permission errors I suppose.

I like the idea of giving the entrypoint script the porous of a environment checker and presenting the directions to fix possible issues (i.e. legacy permissions or plain wrong bind mount perms).

2022-02-13 20:37 UTC, justSem commented
> Thanks for testing my assumed edge case 😅 And yeah I assumed as much that it would run into this issue. Setting the dir to 777 is NEVER a good idea so my apologies for bringing it up at all, was just throwing it out there for the only way to avoid permission errors I suppose.
> 
> I like the idea of giving the entrypoint script the porous of a environment checker and presenting the directions to fix possible issues (i.e. legacy permissions or plain wrong bind mount perms).

I've altered the script to (attempt) to work around this edge-case.
It now assesses ownership, directory and file permissions, and tries to sets them properly.

If it fails it'll exit with an error message instructing on how to resolve the problem.

2022-04-02 15:29 UTC, Saibamen requested changes

2022-04-02 15:29 UTC, Saibamen commented on extra/entrypoint.sh
> +        #Re-run the check
Be consistent in comments
```suggestion
        # Re-run the check
```

2022-04-02 15:29 UTC, Saibamen commented on extra/entrypoint.sh
> +    if [ $(stat -c%u /app/data) !=  $(id -u) ]; then
It would be great to have `/app/data` in variable (used 9 times here)

2022-04-02 15:29 UTC, Saibamen commented on extra/entrypoint.sh
> +   #Check the R/W permissions on the files
Be consistent in comments
```suggestion
   # Check the R/W permissions on the files
```

2022-04-02 15:29 UTC, Saibamen commented on extra/entrypoint.sh
> +        #Re-run the check
Be consistent in comments
```suggestion
        # Re-run the check
```

2022-04-02 15:29 UTC, Saibamen commented on extra/entrypoint.sh
> +        #We're running as root, so we can use setpriv without problems.
```suggestion
        # We're running as root, so we can use setpriv without problems.
```

2022-04-02 15:29 UTC, Saibamen commented on extra/entrypoint.sh
> +        #We're running as a regular user, so we'll launch the app as one.
```suggestion
        # We're running as a regular user, so we'll launch the app as one.
```

2022-04-02 15:29 UTC, Saibamen commented on extra/entrypoint.sh
> +    fi
We are missing echo for "success" here. Directory and file permission has this message
```suggestion
        chown -hRc "$(id -u)":"$(id -g)" /app/data || echo "ERROR: Failed to set file ownership. Please run 'sudo chown -R $(id -u):$(id -g) /path/to/container/volume' to resolve."; exit 1
        echo "File ownership fix succesful! Continuing."
    fi
```

2022-04-03 13:34 UTC, Saibamen approved these changes

2022-04-03 13:44 UTC, justSem commented
@Saibamen Thank you for your feedback and approval! :)

2022-04-15 03:59 UTC, gaby commented
@justSem Doesn't running as a regular user break the ability of sending pings? I remember a long time ago someone else tried this and it broke the Docker image.

2022-04-15 08:35 UTC, justSem commented
> @justSem Doesn't running as a regular user break the ability of sending pings? I remember a long time ago someone else tried this and it broke the Docker image. 

No, ping isn't a privileged unix process.
I run my instance with this script and ping works just fine

2022-04-16 10:58 UTC, k3rnelpan1c-dev commented
While I don't run this script yet, I have Uptime-Kuma deployed in the `restrictive` SCC (Security Context Constraint) of Open Shift and it works just fine.

*I built my own image with a slightly altered version of this script though, since the `restricted` SCC wont allow for any privileged or root running pod, even if its just at startup.

2022-04-16 15:00 UTC, gaby commented
@justSem Here https://github.com/louislam/uptime-kuma/issues/488 it was a long time ago though.

2022-04-19 12:16 UTC, Kurt108 commented
@k3rnelpan1c-dev  could you share your script? Getting Kuma running on Openshift and with a persistent Volume is now as easy as it should be :-o

2022-04-20 09:24 UTC, openstep commented
> While I don't run this script yet, I have Uptime-Kuma deployed in the `restrictive` SCC (Security Context Constraint) of Open Shift and it works just fine.
> 
> *I built my own image with a slightly altered version of this script though, since the `restricted` SCC wont allow for any privileged or root running pod, even if its just at startup.

Hi,

could you please share the info necessary running this in OpenShift? 
Many thanks.

2022-04-20 18:42 UTC, k3rnelpan1c-dev commented
For those curious, yes I will share my config for OCP in a new issue, since it is just marginal connected to this PR.
Sorry to have disrupted the PR topic by my comment :sweat_smile:

2022-04-22 06:34 UTC, beneiltis commented
When are you gonne merge this? :-)

2022-09-05 19:49 UTC, kaysond commented
This would solve my problem of not having root access to my fs!

2022-09-05 20:00 UTC, justSem commented
@Saibamen @louislam Is this going to get merged on any point? Or are there any changes required?

2022-09-06 07:00 UTC, Saibamen commented
@justSem: I don't have write permissions

2022-09-13 10:44 UTC, OlivierAlves commented
May someone merge this it would be really helpful... Thanks !

2022-09-13 10:46 UTC, SirSirae commented
@louislam may someone merge this it would be really helpful ! Thank you !

2022-10-03 20:45 UTC, kaysond commented
Bump. @louislam can we please get this into the next release?

2022-11-15 23:50 UTC, kaysond commented
Bumping again and pinging @louislam

2023-01-29 21:43 UTC, Marck commented
@louislam any change this could come in a release?
I would love to see, I have a volume that is mounted under a non-root user for all my containers use but I cannot use that because this runs as root (which is not needed)

2023-10-04 15:37 UTC, ScmTble approved these changes

2023-12-02 17:05 UTC, chakflying commented
Obsolete by #4052.

2023-12-02 17:05 UTC, closed without merging