1.14.0 translation improvement
louislam/uptime-kuma pull request #1450
Opened 2022-04-04 03:42 UTC by AnnAngela

# Description

These commits make two main changes:

<ol><li>Changes some components to use i18n function:
<ul><li>I have only checked 4 components ( 19b7e2b ), IDK if there are any more strings not using i18n function. <u>And I hope that we can make a tool to check the components automatically.</u></li></ul>
</li><li>Update en & zh-CN translations:
<ul><li>I used `grep` to search `$t("foo")`-like pattern to fill up the missing part of en translation file, IDK if there are any other way to use translation, <u>and I hope that we can also make a tool to fill up this missing part automatically.</u></li></ul>
</li></ol>

## Type of change

Please delete any options that are not relevant.

- Translation update

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I ran ESLint and other linters for modified files
- [x] I have performed a self-review of my own code and tested it
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] My code needed automated testing. I have added them (this is optional task)

## Screenshots (if any)

![image](https://user-images.githubusercontent.com/9762652/161470166-9cb64434-c63f-40df-9f38-9251e1c202c1.png)

2022-04-04 03:47 UTC, AnnAngela commented
@louislam @Computroniks Can you check these changes?

@deluxghost Can you check the zh-CN translation?

2022-04-04 05:32 UTC, deluxghost requested changes

2022-04-04 05:32 UTC, deluxghost commented on src/languages/zh-CN.js
> +    deleteStatusPageMsg: "你确认要删除此状态页吗？",
这些新翻译最好也用“您”，我并非倾向一定用“你”还是“您”，主要是保证整体一致性

后面也有很多地方可能需要改一下

2022-04-04 05:32 UTC, deluxghost commented on src/languages/zh-CN.js
> +    enableProxyDescription: "此代理只有在启用后才会对监控项的网络请求起作用。你可以通过修改激活状态来临时令此代理在所有监控项中禁用。",
```suggestion
    enableProxyDescription: "此代理必须启用才能对监控项的网络请求起作用。您可以通过修改激活状态，临时在所有监控项中禁用此代理。",
```

句子有点别扭

2022-04-04 05:32 UTC, deluxghost commented on src/languages/zh-CN.js
> +    "Don't know how to get the token? Please read the guide:": "不知道如何获取 token？请阅读指南：",
```suggestion
    "Don't know how to get the token? Please read the guide:": "不知道如何获取 Token？请阅读指南：",
```

2022-04-04 05:32 UTC, deluxghost commented on src/languages/zh-CN.js
> +    "The current connection may be lost if you are currently connecting via Cloudflare Tunnel. Are you sure want to stop it? Type your current password to confirm it.": "如果你停止 Cloudflare Tunnel，所有通过
```suggestion
    "The current connection may be lost if you are currently connecting via Cloudflare Tunnel. Are you sure want to stop it? Type your current password to confirm it.": "如果您正在通过 Cloudflare Tunnel 连接，则停止会导致失去当前的连接。确定要停止吗？请输入密码以确认。",
```
这句也有点怪

2022-04-04 05:41 UTC, deluxghost commented
@louislam 

The current translating workflow is a painful process. A translator must do some extra work such as finding new strings, generating new translation files, and using git workflow.

I suggest integrating with any i18n platform that provides an open-source plan.

e.g. Weblate has one:
https://hosted.weblate.org/hosting/

2022-04-04 06:21 UTC, Computroniks approved these changes
Looks good. Just the Chinese changes by @deluxghost

2022-04-04 06:34 UTC, louislam commented on src/components/settings/ReverseProxy.vue
> +                {{ $t("Error Message:") }}
Since cloudflared write all output to `stderr` (standard error), it is acutally not an error message. `Message` would be better.

2022-04-04 09:22 UTC, AnnAngela commented on src/languages/zh-CN.js
> +    "The current connection may be lost if you are currently connecting via Cloudflare Tunnel. Are you sure want to stop it? Type your current password to confirm it.": "如果你停止 Cloudflare Tunnel，所有通过
我的理解是这个`connection`应该是指当前用户通过浏览器访问网站的连接（因为是反代），我做了调整：

> 如果您正在通过 Cloudflare Tunnel 访问网站，则停止可能会导致当前连接断开。您确定要停止吗？请输入密码以确认。

2022-04-04 09:50 UTC, deluxghost approved these changes

2022-04-06 02:32 UTC, AnnAngela commented
@louislam I changed the i18n key that you metioned.

And I found out that [the fs-rmSync.js needs some extra comments](https://github.com/louislam/uptime-kuma/pull/1450/files#diff-464f80b948d20f970dd6da6373a7f66761f61d13426b43587281b7a2f3862c54), so I decided to make a new commit to make it clearer, if you think that it's inappropriate, I can revert this commit, just let me know.

2022-04-06 09:31 UTC, chakflying commented
I think preferably the really long keys are converted to a camel case short form for better readability.

2022-04-06 13:55 UTC, AnnAngela commented
> I think preferably the really long keys are converted to a camel case short form for better readability.

I agree, but I think we should make another PR to change these key since it would make lots translation file being changed.

2022-04-09 06:40 UTC, merged