[WIP]: JSDoc for src/*/*
louislam/uptime-kuma pull request #1550
Opened 2022-04-24 12:47 UTC by Computroniks

# Description

Related to https://github.com/louislam/uptime-kuma/pull/1499

This PR adds JSDoc comments for the `src/*/*` directory. For the full TODO list, see https://github.com/louislam/uptime-kuma/pull/1499

## Type of change

Please delete any options that are not relevant.

- Other

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I ran ESLint and other linters for modified files
- [ ] I have performed a self-review of my own code and tested it
- [ ] I have commented my code, particularly in hard-to-understand areas
  (including JSDoc for methods)
- [ ] My changes generate no new warnings
- [ ] My code needed automated testing. I have added them (this is optional task)

2022-05-16 19:49 UTC, Computroniks commented
Sorry for the delays with this. I am currently doing exams at school so I will try get this done as and when I have time.

2022-06-02 03:04 UTC, chakflying requested changes

2022-06-02 03:04 UTC, chakflying commented on src/components/TagsManager.vue
> +        /** Called as user types input */
```suggestion
        /** Handle pressing Enter key when inside the modal */
```

2022-06-02 03:04 UTC, chakflying commented on src/components/ToggleSection.vue
> +        /** Heading to use */
```suggestion
        /** Heading of the Section */
```

2022-06-02 03:04 UTC, chakflying commented on src/components/ToggleSection.vue
> +        /** Should the selection be open by default? */
```suggestion
        /** Should the section be open by default? */
```

2022-06-02 14:12 UTC, Computroniks commented on src/mixins/mobile.js
> +        /** Called when the screen changes size */
```suggestion
        /** Handle screen resize */
```

2022-06-02 14:12 UTC, Computroniks commented on src/pages/Settings.vue
> +         * For desktop only, mobile do nothing
```suggestion
         * For desktop only, on mobile do nothing
```

2022-06-02 14:12 UTC, Computroniks commented on src/components/Confirm.vue
> +         * @emits "yes" - Notify the parent when Yes is pressed
```suggestion
         * @emits string "yes" Notify the parent when Yes is pressed
```

2022-06-02 14:16 UTC, Computroniks reviewed
Just been through and reviewed the comments to check for any silly errors. I think that this should be ready to be converted to active

2022-06-02 15:17 UTC, chakflying requested changes

2022-06-15 11:29 UTC, merged