Fix apprise integration for Zulip Streams
louislam/uptime-kuma pull request #1604
Opened 2022-05-02 15:24 UTC by c-w

# Description

Currently it's impossible to send a notification from uptime-kuma to a Zulip stream via the apprise integration. This is because some apprise backends (including messaging a Zulip stream) fail if the notification title isn't included in the request:

```
> docker run --entrypoint=apprise --rm caronc/apprise -vv -b "body" "zulip://<bot>@<organization>/<token>/<stream>"
2022-05-02 15:19:04,118 - INFO - Notifying 1 service(s) asynchronously.
2022-05-02 15:19:04,416 - WARNING - Failed to send Zulip notification to <stream>: Bad Request - Unsupported Parameters., error=400.
```

If we add the argument `-t "title"` the notification is sent correctly:

```
> docker run --entrypoint=apprise --rm caronc/apprise -vv -b "body" "zulip://<bot>@<organization>/<token>/<stream>" -t "title"
2022-05-02 15:19:51,545 - INFO - Notifying 1 service(s) asynchronously.
2022-05-02 15:19:51,832 - INFO - Sent Zulip notification to <stream>.
```

To fix this scenario, this pull request adds an environment variable `APPRISE_NOTIFICATION_TITLE` that can be used to include the title argument in the call to apprise.

In an ideal world, the title would be derived from the data that's passed into the send function, but this would be a breaking change. The approach proposed in this pull request is fully backwards compatible as a user of uptime-kuma must explicitly opt-in to the new behavior by setting the new environment variable.

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I ran ESLint and other linters for modified files
- [x] I have performed a self-review of my own code and tested it
- [x] I have commented my code, particularly in hard-to-understand areas (including JSDoc for methods)
- [x] My changes generate no new warnings
- [x] ~My code needed automated testing. I have added them (this is optional task)~

2022-05-02 23:59 UTC, gaby requested changes
I feel like this needs a default value of some sort. Else its not fixing anything.

Maybe the hostname or IP of uptime-kuma.

2022-05-03 00:08 UTC, c-w commented
@gaby I'm totally open to adding a default, however I need to point out that it would be a backwards incompatible change as any deployment of uptime-kuma that uses an apprise backend which doesn't require a title (e.g. Zulip direct messages) will have the behavior changed. I read in the contributing guide [here](https://github.com/louislam/uptime-kuma/blob/ba465447721d0eab8e27ee1924af233ea0ffb25c/CONTRIBUTING.md#-wont-merge) that backwards incompatible changes won't be merged, which is why I went with the opt-in path in this PR. I'm not familiar with all the apprise backends (I just use it for Zulip) so I can't say how prevalent the title requirement actually is. Let me know what you think.

2022-05-03 00:20 UTC, gaby approved these changes

2022-05-03 00:20 UTC, gaby commented
> @gaby I'm totally open to adding a default, however I need to point out that it would be a backwards incompatible change as any deployment of uptime-kuma that uses an apprise backend which doesn't require a title (e.g. Zulip direct messages) will have the behavior changed. I read in the contributing guide [here](https://github.com/louislam/uptime-kuma/blob/ba465447721d0eab8e27ee1924af233ea0ffb25c/CONTRIBUTING.md#-wont-merge) that backwards incompatible changes won't be merged, which is why I went with the opt-in path in this PR. I'm not familiar with all the apprise backends (I just use it for Zulip) so I can't say how prevalent the title requirement actually is. Let me know what you think.

Yeah, I see what you mean now. 👍🏻 looks good to me.

2022-05-03 02:48 UTC, c-w commented
Thanks for the review @gaby. What's the process for getting something merged and published? Anything I can help with?

2022-05-03 02:50 UTC, gaby commented
> Thanks for the review @gaby. What's the process for getting something merged and published? Anything I can help with?

Basically, final review and merge is all done by @louislam

2022-05-06 07:58 UTC, louislam commented
Environment Variable is not encouraged in the project. (https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md)

In this case, if a user want to use Zulip Streams, they need to add the env variable and restart the Uptime Kuma instance in order to activate it.

Also users can setup multiple Apprise notifications, it will affect all Apprise notifications.

My suggestion would be add an optional field `title` in Apprise setup dialog form in the frontend.

```js
if (title is undefined || title is empty string) {
   call apprise without title (original call)
} else {
   call apprise with title (new)
}
```

2022-05-07 15:02 UTC, c-w commented
Thanks for the feedback @louislam. I moved the title configuration from the environment variable to a new input field in the UI in b680371. See below for a screenshot:

![Screenshot of title in apprise setup UI](https://user-images.githubusercontent.com/1086421/167259876-b41855c0-27e9-484e-a7bc-045e78b7705d.png)

I also validated that the alert sends correctly to a stream in my Zulip instance.

2022-05-10 16:47 UTC, merged