Feat: Tags Manager
louislam/uptime-kuma pull request #1690
Opened 2022-05-26 08:56 UTC by chakflying

# Description

- View tags and monitors belonging to that tag
- Edit tag name & color
- Delete a tag (option to delete monitors with that tag?)

## Type of change

- User interface (UI)
- New feature (non-breaking change which adds functionality)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I ran ESLint and other linters for modified files
- [x] I have performed a self-review of my own code and tested it
- [x] I have commented my code, particularly in hard-to-understand areas
  (including JSDoc for methods)
- [x] My changes generate no new warnings
- [ ] My code needed automated testing. I have added them (this is optional task)

## Screenshots (if any)

![image](https://user-images.githubusercontent.com/3271800/210300227-5e8d9bb0-7084-44a2-a976-a3c2e57dd692.png)

![image](https://user-images.githubusercontent.com/3271800/210300254-9b47e292-639b-4dd6-8448-1fa6b3380e63.png)

![image](https://user-images.githubusercontent.com/3271800/210300297-c9561a48-8582-4cc0-a5fe-5aa7b443d3f6.png)

![image](https://user-images.githubusercontent.com/3271800/210301750-e2b498e5-ce68-4264-85fc-fb6a18c93e55.png)

2022-05-26 17:21 UTC, karelkryda commented
It looks amazing

2022-05-27 12:29 UTC, Authorises commented
I'm thinking maybe instead of editing it there, there is just a list of the tags, with an edit button and a delete button and the edit button opens up a modal where you can edit it and see a list of monitors in the list and remove them, change the color using any hex color, and Maybe it would be cool if you could add an icon as well? and then you can save it there.

2022-05-30 09:40 UTC, chakflying commented
There seems to be a lack of high quality color picker library for Vue 3 that supports dark mode. The one from [Vuetify](https://vuetifyjs.com/en/components/color-pickers/#usage) looks nice, but I'm not sure if we should pull in something that big. We could maintain our own, but I'm not sure if it's worth the trouble.

2022-06-30 17:54 UTC, Phyroks commented
+1

2022-09-24 18:22 UTC, bengivre commented
What is the issue not to merge that ?

2022-12-19 11:43 UTC, slumberrad0n commented
What is the current status? When can we expect the function?

2023-01-03 04:39 UTC, chakflying commented
Improved design according to suggestions, the color dropdown will now detect the custom hex color and display accordingly. It's not a lot of functionality but I think it's complicated enough as it is, with edge cases I did not think of. 

 - no custom color picker
 - no option to delete monitors with a tag
 - does not handle individual values set with each monitorTag

2023-01-03 04:47 UTC, chakflying commented
I also realized all the "Saved" messages from the server are not translated when they are displayed in the UI? Might want to add a way to handle this when displaying a toast.

2023-01-03 05:10 UTC, louislam commented
> I also realized all the "Saved" messages from the server are not translated when they are displayed in the UI? Might want to add a way to handle this when displaying a toast.

Yes, @karelkryda had opened a pr for server side translation.
https://github.com/louislam/uptime-kuma/pull/2232

2023-01-12 13:31 UTC, bengivre commented
We are getting there, thank you <3

2023-01-13 12:12 UTC, tminei commented
Awesome!

2023-01-13 13:26 UTC, Computroniks requested changes

2023-01-13 13:26 UTC, Computroniks commented on src/components/TagEditDialog.vue
> +         * @returns {void}
If the function doesn't return anything I don't think the return line should be included 
```suggestion
```

2023-01-13 15:29 UTC, merged

2023-01-13 15:29 UTC, louislam commented
Thanks, work as expected.