Adding GoAlert Notification
louislam/uptime-kuma pull request #2011
Opened 2022-08-23 16:49 UTC by mhkarimi1383

# Description

Adding (GoAlert)[https://goalert.me/]

## Type of change

Please delete any options that are not relevant.

- New feature (non-breaking change which adds functionality)
- This change requires a documentation update (if other notifications are documented)

## Checklist (Nothing yet ;])

- [ ] My code follows the style guidelines of this project
- [ ] I ran ESLint and other linters for modified files
- [ ] I have performed a self-review of my own code and tested it
- [ ] I have commented my code, particularly in hard-to-understand areas
  (including JSDoc for methods)
- [ ] My changes generate no new warnings
- [ ] My code needed automated testing. I have added them (this is optional task)

## Screenshots (if any) (Nothing yet ;])

Please do not use any external image service. Instead, just paste in or drag and drop the image here, and it will be uploaded automatically.

2022-08-23 19:38 UTC, mhkarimi1383 commented
Everything Should be fine my reviews and tests will be finished tomorrow :)

2022-08-24 06:10 UTC, mhkarimi1383 commented
Hello again
`json` content type was not working with GoAlert correctly
So, I migrated to `form-data`
but `form-data` and `axios` where cannot work great together but new version of `axios` has internal support for `form-data` handling, so I upgraded `axios` package

more info:
[axios form-data](https://www.npmjs.com/package/axios#form-data)

2022-08-26 12:34 UTC, Saibamen requested changes

2022-08-26 12:34 UTC, Saibamen commented on server/notification-providers/goalert.js
> +            console.log(resp);
```suggestion
```

2022-08-26 12:34 UTC, Saibamen commented on src/components/notifications/index.js
> +    "GoAlert": GoAlert
```suggestion
    "GoAlert": GoAlert,
```

2022-08-26 21:39 UTC, Saibamen approved these changes

2022-08-27 14:11 UTC, chakflying commented
You should be running npm `v7+` to use the newer version of the lockfile. The node version should not matter as long as it's `14+`.

2022-08-28 17:09 UTC, mhkarimi1383 commented
using npm `8.18.0`
but ci fails

2022-08-28 18:33 UTC, k3rnelpan1c-dev commented
IIRC Node 14 + NPM 7 (the default NPM version with Node 14 IIRC), does not support lockfiles v2.
The general CI `auto-test` use a range of Node Version [14..18] but the `check-linters`only runs 14.

Side note: 14 being a prior LTS is still in maiintainac till May 2023 (https://nodejs.org/en/about/releases/)

2022-08-29 02:28 UTC, chakflying commented
Thanks, I remembered it wrong.

Thing is, CI should still work even with lockfile version mismatch (as it has worked all this time).  I think you broke something else when you regenerated that file on MacOS, somehow the linux dependencies are missing. Anyway I think louislam can handle it if this gets merged.

2022-08-29 20:47 UTC, mhkarimi1383 commented
> Thanks, I remembered it wrong.
> 
> Thing is, CI should still work even with lockfile version mismatch (as it has worked all this time). I think you broke something else when you regenerated that file on MacOS, somehow the linux dependencies are missing. Anyway I think louislam can handle it if this gets merged.

I'm on ArchLinux using `nvm`

2022-08-29 20:49 UTC, mhkarimi1383 commented
```
node --version
v14.6.0
```

```
npm --version
6.14.6
```

What is the ideal version?

2022-08-30 18:56 UTC, k3rnelpan1c-dev commented
okay, took another look, and seems as if the main branch is already using a v2 lock-file. so I am surprised that this hasn't pop up earlier :thinking:

2022-08-30 19:49 UTC, mhkarimi1383 commented
> okay, took another look, and seems as if the main branch is already using a v2 lock-file. so I am surprised that this hasn't pop up earlier :thinking: 
> 
> Edit:
> 
> :man_facepalming: we where looking at the wrong line (like most regular npm users and the lockfile was just a warning not an error):
> 
> > npm ERR! code EBADPLATFORM
> > npm ERR! notsup Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} > (current: {"os":"linux","arch":"x64"})
> > npm ERR! notsup Valid OS:    darwin
> > npm ERR! notsup Valid Arch:  any
> > npm ERR! notsup Actual OS:   linux
> > npm ERR! notsup Actual Arch: x64
> 
> looks like `fsevents@2.3.2` wants the host to be MacOS, yet we on Linux CI and in the container images too.

How main branch is working?

2022-08-31 22:17 UTC, k3rnelpan1c-dev commented
I have not the slightest idea, but a couple of pointers that may be worth evaluating if they are the cause:

* flaky CI (given you are on Arch you could try nuking your current downloaded dependency cache and attempt build to see if that theory applies)
* some funky dependency change within a sub-dependency (if any of the dependencies uses version ranges or similar)

(given that CI passed before regenerating the lockfile it can be either)

Please note that I am merely a CI enthusiast who likes this project and stumbled over your PR. I have no power here, besides trying to help debugging :thinking:

2022-09-01 12:21 UTC, mhkarimi1383 commented
fixed by switching to node v16

2022-09-08 19:34 UTC, merged