Feat: Add http/http keyword timeout option
louislam/uptime-kuma pull request #2142
Opened 2022-09-30 13:18 UTC by zenyr

Tick the checkbox if you understand [x]: 
- [x] I have read and understand the pull request rules.

# Description
- Adds `timeoutMs` to monitor and use it
  - I added 'ms' to make sure the value is NOT a *second*, unlike intervals
- Adds `timeout_ms` to sql patch list
- Fixes #2140, Fixes #2077, Fixes #877

## Type of change

- User interface (UI)
- New feature (non-breaking change which adds functionality)
- Translation update (minor and 🇰🇷  only, running script added a bunch of missing i18n data 😏  )

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I ran ESLint and other linters for modified files
- [x] I have performed a self-review of my own code and tested it
- [x] I have commented my code, particularly in hard-to-understand areas
  (including JSDoc for methods)
- [x] My changes generate no new warnings

## Screenshots (if any)

<img width="1032" alt="image" src="https://user-images.githubusercontent.com/4316558/193277303-4e5caefb-e9f9-4bc8-ac19-add8c7eebe73.png">

2022-10-01 14:55 UTC, Computroniks requested changes
Please don't add the English translations to non English files as it will fall back to the English translation if no other translation is found and will just cause merge conflicts later. I assume you ran `npm run update-language-files`.

@louislam Should we perhaps change this script so it doesn't update all the files and instead only changes a specific one? I don't really see any situation where it it useful and it only seems to create work for contributers when they run it and commit the results, only to be told to revert it.

2022-10-02 08:47 UTC, zenyr commented
I see, let me update the PR to comply the best practice!

2022-10-02 08:59 UTC, zenyr commented on src/languages/ko-KR.js
> +    backupRecommend: "볼륨 또는 데이터 폴더 (./data/) 를 대신 직접 백업해주세요.",
Hello team, I've reverted every un-touched languages change. Please take a look again and see if there's something I could improve. In the meantime I may take a look into the script itself too but I'll refrain myself from mixing 2 features into 1 PR 😄

2022-10-02 09:08 UTC, zenyr commented
I forgot to commit the updated en.js, just pushed one! 😼

2022-10-02 09:55 UTC, Computroniks commented on src/pages/EditMonitor.vue
> +            if (!this.monitor.timeoutMs || this.monitor.timeoutMs >= value * 1000) {
It might be a good idea to have some sort of limit to make sure that the previous request has definitely finished before the next one is sent

2022-10-06 10:27 UTC, zenyr commented on src/pages/EditMonitor.vue
> +            if (!this.monitor.timeoutMs || this.monitor.timeoutMs >= value * 1000) {
If you prefer `less or equal than 80% of the interval seconds` I can change it at once ;) 
Please let me know. (cc. @louislam asking for owner's opinion)

2022-10-07 03:23 UTC, zenyr commented
> > Please don't add the English translations to non English files as it will fall back to the English translation if no other translation is found and will just cause merge conflicts later. I assume you ran `npm run update-language-files`.
> > @louislam Should we perhaps change this script so it doesn't update all the files and instead only changes a specific one? I don't really see any situation where it it useful and it only seems to create work for contributers when they run it and commit the results, only to be told to revert it.
> 
> Oh yes, the command is bad.

Yeah, so I reverted all the artifacts that it created in this PR 😄 Since my team needs this feature and fixes a lot of pending issues is there something I could do to proceed with this PR? I'm sorry if I'm too attached to this feature but due to the fact our VPS network being flakey (like, losing a packet or few randomly) I really would like to use this feature in the stable version..! 😅 

Thank you and ❤️ your work, 
UK made me brave enough to hop into Vue train even though I've been a long time ⚛️ enthusiast.

2022-11-25 08:35 UTC, Eliepse commented
Would love to see this feature merged. Is there anything that prevent it? I'm willing to help if I can :)

2022-11-26 09:57 UTC, Eliepse commented
Just tested this PR, works fine for me 👍 

![image](https://user-images.githubusercontent.com/3075627/204082951-fff52a61-fa98-456f-96ba-c91d7dbe5c7b.png)

2023-01-05 03:23 UTC, usufu commented
@zenyr any docker image for this feature? or how to update docker image with this feature? I need this feature. thx.
why the pull request still not merged? @Computroniks @louislam

2023-01-26 11:50 UTC, i-am-dev commented
Hi.

Any update on this PR and possibly when it will be merged? 

Thanks.

2023-01-26 11:52 UTC, i-am-dev commented
> Hi.
> 
> Any update on this PR and possibly when it will be merged?
> 
> Thanks.

Nevermind. I see now that it is part of the 1.20.0 milestone.

Any due date for the release yet?

Thanks.

2023-01-30 14:34 UTC, louislam commented
Going to work on it. I merged conflict and added `v-if` to the field, so it shows only if http(s) related monitors.

But there are some questions/issues:
- Timeout value must be within the check interval
- As other time related is using second as the unit, I think it should use second instead of millisecond
- I feel `Heartbeat Timeout` is a bit similar to `Heartbeat Interval`, which may be a bit confusing. How about rename it to `Request Timeout`? (If any native English native speakers here, feel free to comment)

2023-02-02 15:39 UTC, lightingman117 commented
USA - Request Timeout is better.

At first, I had no idea what this feature was doing since there is already a timeout notification.

I see that it now allows editing that default value (48000ms) on a per-monitor basis.

2023-02-02 19:07 UTC, chakflying commented
Maybe it would be better to put this in advanced since it might be confusing? We can also have a short description below for more detailed explanation.

2023-02-28 14:22 UTC, alxdlv approved these changes

2023-02-28 22:54 UTC, Computroniks approved these changes

2023-03-07 03:29 UTC, usufu commented
can anyone help merge the code? there are some conflicts must be resolved.

2023-03-13 13:51 UTC, justjcool approved these changes

2023-03-15 08:05 UTC, madan-wego commented
can anyone merge this code ? needed this changes

2023-03-17 09:57 UTC, jeloneal commented
I also want to upvote this one, will be very handy once available. Thanks!

2023-03-24 01:01 UTC, usufu commented
@louislam pls take time to merge this feature, thx.

2023-03-30 08:37 UTC, fredericpellin commented
it could be great if it can be merge for the next release ;) @louislam

2023-04-07 12:21 UTC, usufu commented
@louislam

2023-04-26 10:20 UTC, arthur-lbchn commented
do you have any ETA to have this merged? thanks!

2023-04-26 10:37 UTC, slimshizn commented
Yes please merge. It has been quite a while.

2023-05-30 04:20 UTC, zenyr commented
Thank you for your assistance in resolving the conflicts and all the interests. I have matched them once again, and I would appreciate it if you could review my work when you get the chance! ❤️

2023-05-30 08:32 UTC, kdckrs commented
Awesome! Will be happy when this feature is released so I can finally shut down my other monitoring system.

2023-05-30 08:59 UTC, louislam commented
Hello @zenyr, my last comment is here.

> Going to work on it. I merged conflict and added `v-if` to the field, so it shows only if http(s) related monitors.
> 
> But there are some questions/issues:
> 
>     * Timeout value must be within the check interval
> 
>     * As other time related fields are using second as the unit, I think it should use second instead of millisecond
> 
>     * I feel `Heartbeat Timeout` is a bit similar to `Heartbeat Interval`, which may be a bit confusing. How about rename it to `Request Timeout`? (If any native English native speakers here, feel free to comment)

Also I think @chakflying's concern is reasonable.

> Maybe it would be better to put this in advanced since it might be confusing? We can also have a short description below for more detailed explanation.

2023-05-30 10:25 UTC, zenyr commented
> Hello @zenyr, my last comment is here. [#2142 (comment)](https://github.com/louislam/uptime-kuma/pull/2142#issuecomment-1408729916)
> 
> > Going to work on it. I merged conflict and added `v-if` to the field, so it shows only if http(s) related monitors.
> > But there are some questions/issues:
> > ```
> > * Timeout value must be within the check interval
> > 
> > * As other time related fields are using second as the unit, I think it should use second instead of millisecond
> > 
> > * I feel `Heartbeat Timeout` is a bit similar to `Heartbeat Interval`, which may be a bit confusing. How about rename it to `Request Timeout`? (If any native English native speakers here, feel free to comment)
> > ```
> 
> Also I think @chakflying's concern is reasonable. [#2142 (comment)](https://github.com/louislam/uptime-kuma/pull/2142#issuecomment-1414228676)
> 
> > Maybe it would be better to put this in advanced since it might be confusing? We can also have a short description below for more detailed explanation.
> 
> And @lightingman117 suggested a better name for it:
> 
> [#2142 (comment)](https://github.com/louislam/uptime-kuma/pull/2142#issuecomment-1413942615)

I understand and agree with your points. While setting a timeout longer than the interval may seem.. shooting their own foot 😅 , finding the right balance is indeed crucial.

Regarding the timeout resolution, it's common to work with whole numbers in seconds for consistency. However, if there is a requirement for sub-second resolution, it may be necessary to use floating-point values to accommodate those needs. The choice between using single or float would depend on your choice!

2023-06-20 16:16 UTC, borgogelli commented
> already a timeout notification

@lightingman117 you have written: "there is already a timeout notification"
But where is it ?

2023-07-08 13:26 UTC, louislam commented
The edit page is no longer working, here is the browser console log:

![image](https://github.com/louislam/uptime-kuma/assets/1336778/d475b98b-8246-4362-9462-c94a06e6dc31)

2023-07-14 07:34 UTC, zenyr commented on src/pages/EditMonitor.vue
> +            this.monitor.timeout = Math.Max(0, Math.min(timeout, maxTimeout));
This is a very amateur like mistake from my side. My bad!

2023-07-14 07:38 UTC, zenyr commented
Just resolved "Math.Max" typo for the PR. Sorry for the hassle! I must've been too excited when I added the line!

2023-07-15 16:25 UTC, louislam commented
Test it again, unfortunately, newly created monitor doesn't seem to be working. 

Weird default value:
![image](https://github.com/louislam/uptime-kuma/assets/1336778/fd40c2f2-b7b0-4e88-9b33-119bcd83d9b8)

I manually inputted 48 seconds, but the monitor timeout in 48ms. Forgot to x1000?
![image](https://github.com/louislam/uptime-kuma/assets/1336778/2709a8e9-6e55-4aa9-8880-879f6ab0d442)

Old monitor, the original interval is 60s and the request time is 48s, then I change the interval to 30s.

The request time became this:
![image](https://github.com/louislam/uptime-kuma/assets/1336778/3bb8f49b-7067-4f3e-8a4f-209436b6ee6f)

2023-07-16 04:58 UTC, zenyr commented
Sure! I will ping you again once I finish testing the code first, I had issues setting up dev env on a new device(for personal reasons) but definitely will do!

2023-07-18 04:33 UTC, zenyr commented
Fixed few things
1. Co-located timeout field with intervals, making their relation more clear
2. Used different formula to clamp to 80%, resulting better fraction numbers for edit/add view. ( `t*0.8` => `~~(t * 8)/10`)
3. Displays 80% inside the UI that directly depicts `0 == default value(80%)` (since timeout of 0 literally makes 0 sense)
  - This is not visible in the GIF below but in the source code, `monitor.timeout || clampTimeout( interval )` is used.
![timeout-test](https://github.com/louislam/uptime-kuma/assets/4316558/29ea6a72-4e81-4a45-bbb5-64a1109aec2d)
4. Added db migration code to the last place

2023-07-22 13:55 UTC, CommanderStorm commented on src/pages/EditMonitor.vue
> +                    timeout: this.interval * 0.8, // previous default value
Previous compared to what?
I think this comment will not age well ^^

```suggestion
                    timeout: this.interval * 0.8,
```

2023-08-06 16:14 UTC, merged