Added userchoice heartbeat bar
louislam/uptime-kuma pull request #217
Opened 2021-08-15 18:52 UTC by Ponkhy

As mentioned in #206 was it a little hard to read the Monitor Name on smaller screens.
So i added the possibility that the user can choose how the heartbeat bar should look like.

**Settings Page:** 
![Settings](https://i.imgur.com/mZQVTGa.png)

**Example Normal:**
![Normal](https://i.imgur.com/BqTGkBe.png)

**Example Bottom:**
![Bottom](https://i.imgur.com/JUk39GR.png)

**Example Node:**
![Node](https://i.imgur.com/87JWZ6Y.png)

2021-08-15 18:54 UTC, Ponkhy commented
I also added a bit more space over the badge on mobile screens to it would look a more centered.

2021-08-16 14:36 UTC, Saibamen requested changes

2021-08-16 14:36 UTC, Saibamen commented on src/mixins/theme.js
> +            userHeartbeatBar: localStorage.heartbeatBarTheme
```suggestion
            userHeartbeatBar: localStorage.heartbeatBarTheme,
```

2021-08-16 14:36 UTC, Saibamen commented on src/mixins/theme.js
> +        //Default Heartbeat Bar
```suggestion
        // Default Heartbeat Bar
```

2021-08-16 14:36 UTC, Saibamen commented on src/mixins/theme.js
> +        if (! this.userHeartbeatBar) {
```suggestion
        if (!this.userHeartbeatBar) {
```

2021-08-17 00:59 UTC, Ponkhy commented
@Saibamen It should be done

2021-08-17 07:24 UTC, Saibamen approved these changes

2021-08-17 11:45 UTC, louislam commented
Found a strange bug, it only appears if your switch to another page and back to "Settings" page.

https://user-images.githubusercontent.com/1336778/129719974-76debf13-ba8a-42dc-84c1-09459319cab8.mp4

2021-08-17 11:58 UTC, Ponkhy commented
> Found a strange bug, it only appears if your switch to another page and back to "Settings" page.
> 
>  a.mp4

That's really strange, in the last seconds (0:11-1:12) you can even see a bit of the heartbeat bar.
I'll try to find some time later to figure it out.

2021-08-17 13:46 UTC, Ponkhy commented
@louislam Okay it's fixed with the latest commit `77369bd`. I was only able to get it work by adding a `:key`.
I've also used `v-show` instead of `v-bind:class` now and removed the `.hideHeartbeatBar` class.

2021-08-18 07:16 UTC, merged