[empty commit] pull request for 'toast-notification-timeout-setting'
louislam/uptime-kuma pull request #2555
Opened 2023-01-06 12:30 UTC by BercziSandor

⚠️⚠️⚠️ Since we do not accept all types of pull requests and do not want to waste your time. Please be sure that you have read pull request rules:
https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md#can-i-create-a-pull-request-for-uptime-kuma

Tick the checkbox if you understand [x]: 
- [x] I have read and understand the pull request rules.

# Description
Currently there is no time limit on error messages; this behavior can be very annoying: the user has to close many notifications before being able to use the interface. (20s for warnings)
To remedy this, the following should/could be changed:
1) Setting the timeout for toast notifications (0 or blank: no timeout). It can be set in the settings menu, separately for warnings and errors.
2) Option to close all notification windows in one step.

Fixes #(issue)

## Type of change

Please delete any options that are not relevant.

- User interface (UI)
- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I ran ESLint and other linters for modified files
- [ ] I have performed a self-review of my own code and tested it
- [ ] I have commented my code, particularly in hard-to-understand areas
  (including JSDoc for methods)
- [ ] My changes generate no new warnings
- [ ] My code needed automated testing. I have added them (this is optional task)

## Screenshots (if any)

Please do not use any external image service. Instead, just paste in or drag and drop the image here, and it will be uploaded automatically.

2023-01-07 19:09 UTC, louislam commented
That is great. It will be accepted.

The timeout setting could be under `Settings` > `Notifications`.

2023-01-11 20:34 UTC, BercziSandor commented
@louislam : Do you have a doc describing the development steps for Kuma? (How to create the development environment, how to test etc.)
(I am not a frontend developer but I learn fast ;)

2023-01-19 22:06 UTC, chakflying commented
Since this is only used in the browser, you can keep it simple by storing it in `localStorage`, like how the theme settings are kept. If you really want to keep it on the server, I guess you can take a look at how `initServerTimezone` is done:

1. `afterLogin` (in `server/server.js:1599`), the server sends a command through the socket to tell the frontend to do something
2. The frontend receive this in `src/mixins/socket.js:277`, and send the results needed back.

I guess you would similarly sends this setting afterLogin, and the frontend receive it and store it somewhere.

2023-01-20 23:19 UTC, chakflying commented
- If the user does not set the setting, it defaults to no timeout, which is not the previous behavior
- The default in the UI is not the previous default, which is 20 seconds for Up and none for down
- Personally would prefer 0 for disabled to be more consistent with other settings
- Would be great if you can update the PR title and squash to clean up the commits.

2023-01-21 10:28 UTC, Computroniks requested changes

2023-01-21 10:28 UTC, Computroniks commented on src/layouts/Layout.vue
> +        deleteNotifications() {
Would it be possible to add jsdoc for the methods you have added

2023-01-21 20:29 UTC, BercziSandor commented
> * If the user does not set the setting, it defaults to no timeout, which is not the previous behavior
See Notifications.vue / mounted()

> * The default in the UI is not the previous default, which is 20 seconds for Up and none for down
Fixed.

> * Personally would prefer 0 for disabled to be more consistent with other settings
-1: no timeout: it won't disappear.
0: no notification window: it disappears immediately

> * Would be great if you can update the PR title and squash to clean up the commits.
Fixed.

2023-06-07 16:18 UTC, louislam commented
There are 68 files changed. I think something went wrong.

2023-09-06 11:57 UTC, CommanderStorm commented
@louislam @BercziSandor 
given that https://github.com/louislam/uptime-kuma/pull/3441 was merged, I think we can safely close this one too ^^

2023-09-06 12:04 UTC, closed without merging