update lang file to latest version
louislam/uptime-kuma pull request #2657
Opened 2023-01-22 21:37 UTC by black23

⚠️⚠️⚠️ Since we do not accept all types of pull requests and do not want to waste your time. Please be sure that you have read pull request rules:
https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md#can-i-create-a-pull-request-for-uptime-kuma

Tick the checkbox if you understand [x]: 
- [x ] I have read and understand the pull request rules.

# Description

Fixes #(issue)

## Type of change

Please delete any options that are not relevant.

- Translation update

## Checklist

- [x ] My code follows the style guidelines of this project
- [ ] I ran ESLint and other linters for modified files
- [ x] I have performed a self-review of my own code and tested it
- [ ] I have commented my code, particularly in hard-to-understand areas
  (including JSDoc for methods)
- [ ] My changes generate no new warnings
- [ ] My code needed automated testing. I have added them (this is optional task)

## Screenshots (if any)

Please do not use any external image service. Instead, just paste in or drag and drop the image here, and it will be uploaded automatically.

2023-01-23 02:36 UTC, louislam commented
`
/home/runner/work/uptime-kuma/uptime-kuma/src/languages/cs-CZ.js
  246:4  error  Parsing error: Unexpected token, expected "," (246:4)
`

2023-01-24 05:10 UTC, YehowahLiu requested changes

2023-01-24 05:10 UTC, YehowahLiu commented on src/languages/cs-CZ.js
> +    wayToGetZohoCliqURL: "Informace o tom, jak vytvořit URL adresu webhooku naleznete {0}."
```suggestion
    wayToGetZohoCliqURL: "Informace o tom, jak vytvořit URL adresu webhooku naleznete {0}.",
```

2023-01-24 05:23 UTC, louislam commented
#2659 

Oh no, I just realized that you guys translated a same language file at the same time. 

@Buchtic @black23

2023-01-24 06:58 UTC, louislam commented
Since there are a lot of conflicts and we are switching to Weblate, I would suggest that it should be handled on Weblate later.

2023-01-24 07:01 UTC, black23 commented
I just write comment about Weblate :-) It's logcal step, best for collaboration.

2023-01-24 09:03 UTC, louislam commented
> I just write comment about Weblate :-) It's logical step, best for collaboration.

Just finished setup Weblate, you could try to copy your translated word on https://weblate.kuma.pet. Sorry for the inconvenience.

2023-01-24 09:23 UTC, black23 commented
Great news! Lets go translate!

Thank you

út 24. 1. 2023 v 10:03 odesílatel Louis Lam ***@***.***>
napsal:

> I just write comment about Weblate :-) It's logical step, best for
> collaboration.
>
> Just finished setup Weblate, you could try to copy your translated word on
> https://weblate.kuma.pet. Sorry for the inconvenience.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/louislam/uptime-kuma/pull/2657#issuecomment-1401583689>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABKC5CFLCCFF23HCIQXXDK3WT6LF7ANCNFSM6AAAAAAUDGPDBY>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-01-31 14:42 UTC, louislam commented
I saw you had worked on Weblate, thank you so much!

2023-01-31 14:42 UTC, closed without merging