Inline Keyboard for Telegram Alert
louislam/uptime-kuma pull request #2734
Opened 2023-02-07 15:18 UTC by BlackYuzia

⚠️⚠️⚠️ Since we do not accept all types of pull requests and do not want to waste your time. Please be sure that you have read pull request rules:
https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md#can-i-create-a-pull-request-for-uptime-kuma

Tick the checkbox if you understand [x]: 
- [x] I have read and understand the pull request rules.

# Description

Hi there.
I add inline keyboard use (like in discord webhooks, check screenshots)
Hope this improves view of telegram alert messages. 

## Type of change

- Other
- Alert changes

## Checklist

- [ ] My code follows the style guidelines of this project
- [x] I ran ESLint and other linters for modified files
- [x] I have performed a self-review of my own code and tested it
- [x] I have commented my code, particularly in hard-to-understand areas
  (including JSDoc for methods) (**I try to do this**)
- [x] My changes generate no new warnings
- [ ] My code needed automated testing. I have added them (this is optional task)

## My Own Checklist

- [x] Test telegram alert (when service UP or DOWN)
- [x] Test telegram alert (when test alert)

## Screenshots 
![image](https://user-images.githubusercontent.com/25010528/217282823-f5aa89c1-d2be-4746-9ac7-b5620f34cab3.png)
![image](https://user-images.githubusercontent.com/25010528/217284164-6b6c2330-c0ee-4a39-abe6-a132c3874137.png)
I try get the same result as in discord webhooks
![image](https://user-images.githubusercontent.com/25010528/217284370-c9c6e039-848c-4765-afab-18da9b38d383.png)

But, I found a bug (? probably) so maybe I should also duplicate title (name and status) to the body of telegram message? 🤔 
Empty message, so you can't see about what service you get alert:
![image](https://user-images.githubusercontent.com/25010528/217283002-7ceacb6b-df6d-46ee-8694-a0aaaf451dda.png)
But, that could be fixed by a few methods.

2023-05-20 22:39 UTC, CommanderStorm requested changes
I have a few hard questions:
- why have you included information like `Ping` (which is not in discord embeds)
- Why is this better than a text message?
- Is it possible to replace only some part of the message with the inline keyboard?
  Imo only the last one benefits from the keyboard, the other ones could just as easily be in the text (or not there at all)

2023-05-20 22:39 UTC, CommanderStorm commented on server/notification-providers/telegram.js
> +        ];
please refactor this code to be eazier readable through less code repetition

2023-05-20 22:39 UTC, CommanderStorm commented on server/notification-providers/telegram.js
> +            }
If heartbeatJSON is null, this is a general message, not testing
```suggestion
```

2023-05-20 22:39 UTC, CommanderStorm commented on server/notification-providers/telegram.js
> +                        // https://core.telegram.org/bots/api#inlinekeyboardbutton
Move these up where the inlineKeyboard is defined, respectively.
Comments rot, these will particularly quickly.

2023-05-20 22:39 UTC, CommanderStorm commented on server/notification-providers/telegram.js
> +                    text: "­", // ALT + 0173 (that string isn't empty!)
Please explain why this is nessesary/better

2023-05-20 22:39 UTC, CommanderStorm commented on server/notification-providers/telegram.js
> +        }
why is this in the inline keyboard and not in the text?

2023-05-20 22:39 UTC, CommanderStorm commented on server/notification-providers/telegram.js
> +        const emoji = status ? "✅" : "❌";
why is the emoji extracted?

2023-05-20 22:39 UTC, CommanderStorm commented on server/notification-providers/telegram.js
> +    getTitle(name, status) {
why is this function extracted?

2023-07-14 18:47 UTC, louislam commented
I checked the inline keywords is likely used for multiple choices or buttons. I feel that the info/message displaying on buttons is a bit strange to me.

https://core.telegram.org/bots/2-0-intro#new-inline-keyboards

2023-12-03 18:00 UTC, closed without merging