Use API v2 for Bark notification
louislam/uptime-kuma pull request #2759
Opened 2023-02-11 20:18 UTC by harryzcy

⚠️⚠️⚠️ Since we do not accept all types of pull requests and do not want to waste your time. Please be sure that you have read pull request rules:
https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md#can-i-create-a-pull-request-for-uptime-kuma

Tick the checkbox if you understand [x]: 
- [x] I have read and understand the pull request rules.

# Description

Bark notification provider offers a API v2 and should be preferred ([see its doc](https://github.com/Finb/bark-server/blob/master/docs/API_V2.md)). The new API uses standard POST requests to send notifications.

## Type of change

Please delete any options that are not relevant.

- Other

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I ran ESLint and other linters for modified files
- [x] I have performed a self-review of my own code and tested it
- [x] I have commented my code, particularly in hard-to-understand areas
  (including JSDoc for methods)
- [x] My changes generate no new warnings
- [ ] My code needed automated testing. I have added them (this is optional task)

## Screenshots (if any)

2023-02-12 09:25 UTC, louislam commented
Will it affects current users whose bark server is API v1?

2023-02-12 20:02 UTC, harryzcy commented
No. In the official [bark project](https://github.com/Finb/bark-server), its API v2 was added in Feb, 2021, even before Uptime Kuma supports bark notifications (in Oct 2021). So all users using Bark should already have API v2 support. It won't break anything for current users.

2023-02-14 01:44 UTC, louislam commented
I am still concerning, because users could possibly be using the old version of bark-server?

If yes, it will be a breaking change and the current implementation is a better handling for both old and new bark-servers.

cc: @Lakr233

2023-02-14 05:39 UTC, Lakr233 commented
I don't even know there is a v2 API of bark server.................... 🥲

we could put a notice? > Bark API v2 is required?

2023-02-25 04:15 UTC, harryzcy commented
If we have to keep API v1 version, then I think it's good to introduce API v2 as a separate provider. 
What do you think @louislam

2023-07-12 04:22 UTC, Lakr233 approved these changes

2023-07-12 06:23 UTC, louislam commented
> If we have to keep API v1 version, then I think it's good to introduce API v2 as a separate provider. What do you think @louislam

A separate provider may be too much. You can add a dropdown for selecting V1/V2 api. 


- Notifications that setup before this pr:
Keep using V1 

- New notifications:
Default value = V2

2023-09-15 19:01 UTC, harryzcy commented
> > If we have to keep API v1 version, then I think it's good to introduce API v2 as a separate provider. What do you think @louislam
> 
> A separate provider may be too much. You can add a dropdown for selecting V1/V2 api.
> 
> * Notifications that setup before this pr:
>   Keep using V1
> * New notifications:
>   Default value = V2

Sure, it's now implemented

2023-09-16 01:23 UTC, chakflying requested changes
Also, new translated string should be added to `en.json`.

2023-09-16 01:23 UTC, chakflying commented on src/components/notifications/Bark.vue
> +        <select id="Bark Sound" v-model="$parent.notification.apiVersion" class="form-select" required>
```suggestion
        <label for="Bark API Version" class="form-label">{{ $t("Bark API Version") }}</label>
        <select id="Bark API Version" v-model="$parent.notification.apiVersion" class="form-select" required>
```

2023-09-17 03:27 UTC, chakflying requested changes
If users created the notification in an older version, the value would be null? I think added a check here would make sure that they continue to use v1.

2023-09-17 03:27 UTC, chakflying commented on server/notification-providers/bark.js
> +        if (notification.apiVersion == "v1") {
```suggestion
        if (notification.apiVersion === "v1" || notification.apiVersion == null) {
```

2023-09-21 13:08 UTC, merged