✨ feat: add elasticsearch monitor (`index` and `query`)
louislam/uptime-kuma pull request #3322
Opened 2023-06-27 15:17 UTC by mhkarimi1383

⚠️⚠️⚠️ Since we do not accept all types of pull requests and do not want to waste your time. Please be sure that you have read pull request rules:
https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md#can-i-create-a-pull-request-for-uptime-kuma

Tick the checkbox if you understand [x]: 
- [x] I have read and understand the pull request rules.

# Description

Adding Elasticsearch monitors to index data and query data

## Type of change

Please delete any options that are not relevant.

- User interface (UI)
- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I ran ESLint and other linters for modified files
- [ ] I have performed a self-review of my own code and tested it
- [ ] I have commented my code, particularly in hard-to-understand areas
  (including JSDoc for methods)
- [ ] My changes generate no new warnings
- [ ] My code needed automated testing. I have added them (this is optional task)

## Screenshots (if any)

Please do not use any external image service. Instead, just paste in or drag and drop the image here, and it will be uploaded automatically.

2023-06-28 06:25 UTC, louislam commented
Hello, I am trying to restructure the monitor types logic from `monitor.js` into separated files.

You can copy a boilerplate from this pr:
https://github.com/louislam/uptime-kuma/pull/3178/files

2023-06-28 06:32 UTC, mhkarimi1383 commented
> Hello, I am trying to restructure the monitor types logic from `monitor.js` into separated files.
> 
> You can copy a boilerplate from this pr:
> https://github.com/louislam/uptime-kuma/pull/3178/files

Hi, I will do it, I also loved the new structure

It would be great if we could get fields on monitor change on frontend from backend instead of using `v-if`

2024-01-06 07:14 UTC, 919927181 commented
At present, the solution for ElasticSearch log alerts is ElastAlert, but it requires maintenance of configuration files and is difficult to manage. Therefore, we hope that Uptime Kuma can support this feature. 

@louislam May I ask when is the expected release time for this feature?

2024-01-06 09:35 UTC, CommanderStorm commented
> May I ask when is the expected release time for this feature

As any self-respecting open source project we don't offer esitmates. See [#noestimates](https://www.youtube.com/watch?v=QVBlnCTu9Ms) for a more in-depth discussion.

Currently, there has not been a mergable attempt.
This PR is not in a mergable state (see the diff, this mostly is unrelated changes).
=> This feature will get reviewed in one of the [future release milestones](https://github.com/louislam/uptime-kuma/milestones) once/if this gets done.

2024-04-27 21:36 UTC, CommanderStorm commented
@mhkarimi1383 you can drop b8bcb6f13acef9d56fd99485617e9f295ed49d0d from this PR via the following commands (you have disabled maintainer write access)

```
git revert b8bcb6f13acef9d56fd99485617e9f295ed49d0d
npm i
git add .
git revert --continue
```

If you are stuck wondering what needs to be done to push this PR over the line, we have recently improved our contribution guide for new monitors:
https://github.com/louislam/uptime-kuma/blob/126d6cd912cbae2602d643916773e1fd064c4567/CONTRIBUTING.md#:~:text=new%20monitoring%20types

2024-04-29 13:51 UTC, mhkarimi1383 commented
@CommanderStorm will do that
I have stopped because this project was in refactor state and I thought that monitor type section of project will change

2024-04-29 14:17 UTC, mhkarimi1383 commented
> @mhkarimi1383 you can drop [b8bcb6f](https://github.com/louislam/uptime-kuma/commit/b8bcb6f13acef9d56fd99485617e9f295ed49d0d) from this PR via the following commands (you have disabled maintainer write access)
> 
> ```
> git revert b8bcb6f13acef9d56fd99485617e9f295ed49d0d
> npm i
> git add .
> git revert --continue
> ```
> 
> If you are stuck wondering what needs to be done to push this PR over the line, we have recently improved our contribution guide for new monitors: https://github.com/louislam/uptime-kuma/blob/126d6cd912cbae2602d643916773e1fd064c4567/CONTRIBUTING.md#:~:text=new%20monitoring%20types
> 
> Is there something that you need help with?

I have done these steps

2024-04-29 14:17 UTC, mhkarimi1383 commented
Also edit is allowed by maintainers

2024-04-29 15:46 UTC, CommanderStorm commented
> I have stopped because this project was in refactor state and I thought that monitor type section of project will 

True.
Since then we have documented this part (how to add new monitors) in our contribution guide https://github.com/louislam/uptime-kuma/blob/19e8c75c3b7fa8e1e9d6675372785dc37a8ef04e/CONTRIBUTING.md#:~:text=new%20monitoring%20types
Older monitors still need to be refactored for the most part, but that should not be a merge blocker.

2024-04-29 20:05 UTC, mhkarimi1383 commented
@CommanderStorm 
Will do it
Finally, I see devcontainers here :)

2024-05-02 08:45 UTC, mhkarimi1383 commented
@CommanderStorm 
Branch updated

2024-05-19 20:35 UTC, CommanderStorm requested changes
> Since then we have [documented this part (how to add new monitors) in our contribution guide](https://github.com/louislam/uptime-kuma/blob/19e8c75c3b7fa8e1e9d6675372785dc37a8ef04e/CONTRIBUTING.md#:~:text=new%20monitoring%20types). 
Older monitors still need to be refactored for the most part, but that should not be a merge blocker.

Okay.. what I meant by my above comment was that this PR is missing the Frontend and the backend partially.

=> please include:
- the Frontend (see contribution guide what files need to be changed)
- the Monitor (see contribution guide what files need to be changed)
- how to setup elasicsearch in the simplest way ("how to test the PR")

2025-05-18 20:48 UTC, CommanderStorm commented
I don't think that this PR in its currrent form will ever get to a mergable state => closing the PR.
If this changes, we can reopen

2025-05-18 20:48 UTC, closed without merging