Feat: Toast notification timeout settings
louislam/uptime-kuma pull request #3441
Opened 2023-07-18 04:34 UTC by chakflying

⚠️⚠️⚠️ Since we do not accept all types of pull requests and do not want to waste your time. Please be sure that you have read pull request rules:
https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md#can-i-create-a-pull-request-for-uptime-kuma

Tick the checkbox if you understand [x]: 
- [x] I have read and understand the pull request rules.

# Description

Fixes #2116

This is a continuation of #2555, with various changes applied to improve usability and code organization. Settings is stored to `localStorage` on change, so the "Save" button is not needed. Settings are applied to the toast instance default, which will apply to all toast notifications of the same type.

A new button to clear all toast notification is added to the bottom of the toasts stack. The individual close button for each toast is set to show on hover since the close all button should satisfy most needs.

## Type of change

- User interface (UI)
- New feature (non-breaking change which adds functionality)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I ran ESLint and other linters for modified files
- [x] I have performed a self-review of my own code and tested it
- [x] I have commented my code, particularly in hard-to-understand areas
  (including JSDoc for methods)
- [x] My changes generate no new warnings
- [ ] My code needed automated testing. I have added them (this is optional task)

## Screenshots (if any)

![image](https://github.com/louislam/uptime-kuma/assets/3271800/060e01cd-e2e5-4bfb-bb6c-52b2232c8e79)

2023-07-20 00:57 UTC, chakflying commented
Thinking about this, it's probably not a good idea for the setting to affect the system messages. Changed back to the setting affecting monitor toast notifications only.

2023-07-27 22:34 UTC, CommanderStorm commented
Could you add the following to the PR description?
Resolves https://github.com/louislam/uptime-kuma/issues/1085
Resolves https://github.com/louislam/uptime-kuma/issues/841

2023-08-05 11:24 UTC, Computroniks requested changes

2023-08-05 11:24 UTC, Computroniks commented on src/util-frontend.js
> +export function getToastSuccessTimeout() {
```suggestion
/**
 * Get timeout for success toasts
 * @returns {(number|boolean)} Timeout in ms. If false timeout disabled.
 */
export function getToastSuccessTimeout() {
```

2023-08-05 11:24 UTC, Computroniks commented on src/util-frontend.js
> +export function getToastErrorTimeout() {
```suggestion
/**
 * Get timeout for error toasts
 * @returns {(number|boolean)} Timeout in ms. If false timeout disabled.
 */
export function getToastErrorTimeout() {
```

2023-08-05 11:24 UTC, Computroniks commented on src/components/settings/Notifications.vue
> +        toastSuccessTimeoutSecs: function (newTimeout) {
```suggestion
        toastSuccessTimeoutSecs(newTimeout) {
```

This seems to fit better with how it is styled in the rest of the code base and in the VueJS docs.

2023-08-05 11:24 UTC, Computroniks commented on src/components/settings/Notifications.vue
> +        toastErrorTimeoutSecs: function (newTimeout) {
```suggestion
        toastErrorTimeoutSecs(newTimeout) {
```

2023-08-05 11:24 UTC, Computroniks commented on src/util-frontend.js
> +import { TYPE, POSITION } from "vue-toastification";
```suggestion
import { POSITION } from "vue-toastification";
```

Linter warning

2023-08-10 14:09 UTC, domdfcoding commented
Are there any instructions for building the docker image from source? I looked but I can only find npm instructions, and my current setup is through docker. I'd like to give this PR a try as it's a feature I'm looking forward to.

2023-08-10 14:20 UTC, Computroniks commented
You should be able to use the pre built docker image for this PR by following these instructions in the wiki
https://github.com/louislam/uptime-kuma/wiki/Test-Pull-Requests

2023-09-06 11:52 UTC, merged

2024-08-26 10:25 UTC, mezza93 commented
> Are there any instructions for building the docker image from source? I looked but I can only find npm instructions, and my current setup is through docker. I'd like to give this PR a try as it's a feature I'm looking forward to.

Sorry but where did you find the instructions for NPM upgrade for this one?

2024-08-26 11:12 UTC, CommanderStorm commented
See #4500 for the steps where help is appreciated to get v2.0 shipped