UPTM-14 - Dashboard Display on vertical 4K screen
louislam/uptime-kuma pull request #3451
Opened 2023-07-19 09:04 UTC by gitstart

Here is the GitStart Ticket for this pull request: [UPTM-13](https://developers.gitstart.com/client/Uptime-Kuma/ticket/UPTM-13)

- Please mark your PR as "ready for review" when you have completed all requirements.
- Please ensure that your PR is reviewed by at least 2 people after you have completed it.
- Comments for review or requested changes from the upstream client will be notified to you by email and will also show on the [ticket page](https://developers.gitstart.com/client/Uptime-Kuma/ticket/UPTM-13).
- After the PR is merged on the upstream, please merge this PR.
- If there exist merge conflicts on your current PR and you have to close the PR instead of merging it, please go to the [ticket page](https://developers.gitstart.com/client/Uptime-Kuma/ticket/UPTM-13) to manually finish the task that is related to this PR.

### Loom video
https://www.loom.com/share/ef13e3e6a9b34f7d84f568ec1d1fdd6c
Happy hacking! 🎉

---
This code was written and reviewed by GitStart Community. Growing great engineers, one PR at a time.

2023-07-29 00:15 UTC, CommanderStorm requested changes
I cannot reproduce the fix.

Is my testing environment off?
My current testing is that I have this page open (slightly zoomed out on a 5k screen):
![image](https://github.com/louislam/uptime-kuma/assets/26258709/ec05937a-19d4-411a-b854-9687dbfad506)
My understanding, was that reloading the page should show more heartbeats, right?

I have also tried this reproduction step:
![image](https://github.com/louislam/uptime-kuma/assets/26258709/d2b430c0-d5ac-479c-9d53-2a41649fef79)

How can this PR be tested?

2023-07-29 00:17 UTC, CommanderStorm commented
(if possible)
Could you add the following to the description? (This will make merging this PR automatically close the linked issue)
`Resolves https://github.com/louislam/uptime-kuma/issues/2993`

2023-07-31 09:06 UTC, louislam commented
I tested it on my 4k tv, it is OK, need to refresh the page though.

<img src="https://github.com/louislam/uptime-kuma/assets/1336778/ceaac726-fd12-4fed-b0b7-dceb14bc0c79" height=300>

2023-07-31 09:09 UTC, louislam commented on src/pages/DashboardHome.vue
> +                }
Should we change it to the window resize event rather than inside here?

2023-08-03 13:07 UTC, merged