fix for #3351: restructure alert actions, add 'visit site' button
louislam/uptime-kuma pull request #3886
Opened 2023-10-13 11:55 UTC by DaanMeijer

Tick the checkbox if you understand [x]:
- [x] I have read and understand the pull request rules.

# Description

Fixes #3351: adds the monitor url as a button to the slack message. Also, restructured the code which adds the "Visit Uptime Kuma" button to be more readable and modular.

## Type of change

Please delete any options that are not relevant.

- New feature (non-breaking change which adds functionality)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I ran ESLint and other linters for modified files
- [x] I have performed a self-review of my own code and tested it
- [x] I have commented my code, particularly in hard-to-understand areas
  (including JSDoc for methods)
- [x] My changes generate no new warnings

2023-10-13 22:31 UTC, CommanderStorm commented on server/notification-providers/slack.js
> +            const blocks = [];
```suggestion
            const blocks = [];
```

2023-10-13 22:31 UTC, CommanderStorm commented on server/notification-providers/slack.js
> +            //only add this block if we have actions
```suggestion
```

2023-10-13 22:31 UTC, CommanderStorm commented on server/notification-providers/slack.js
> +
```suggestion
```

2023-10-13 22:33 UTC, CommanderStorm commented on server/notification-providers/slack.js
> +            const actions = [];
Please extract the action generation into another function to not make this function too large

2023-10-13 22:33 UTC, CommanderStorm commented on server/notification-providers/slack.js
> +            const blocks = [];
Extracting the block-generation might be a good usage of another method

2023-10-13 22:37 UTC, CommanderStorm commented
(sorry for providing everything as separate reviews, I thought I was in a review session)

Also, please attach screenshots of the before/after result to make sure that this has been tested

2023-10-13 23:04 UTC, septemberservices commented
Before:
![image](https://github.com/louislam/uptime-kuma/assets/35113929/3f5fd021-ee7f-47f5-818b-71d834203493)


After: 
![image](https://github.com/louislam/uptime-kuma/assets/35113929/906eb7dc-def3-4ce5-a429-c87cb94ab7f8)

2023-10-13 23:29 UTC, CommanderStorm requested changes
Looks much more maintainable 👍🏻 
Please address the style-warnings and issing JSDoc comments of eslint
Don't forget to resolve comments which are done ^^

2023-10-13 23:29 UTC, CommanderStorm commented on server/notification-providers/slack.js
> +    static async buildBLocks(monitorJSON, heartbeatJSON, textMsg, msg){
```suggestion
    static async buildBlocks(monitorJSON, heartbeatJSON, textMsg, msg){
```

2023-10-13 23:29 UTC, CommanderStorm commented on server/notification-providers/slack.js
> +        //only add this block if we have actions
nit: This comment is obvious and does not add any additional context ^^

```suggestion
```

2023-10-13 23:29 UTC, CommanderStorm commented on server/notification-providers/slack.js
> +
```suggestion
```

2023-10-13 23:29 UTC, CommanderStorm commented on server/notification-providers/slack.js
> +            //finally, build the entire slack request object
see below
```suggestion
```

2023-10-13 23:29 UTC, CommanderStorm commented on server/notification-providers/slack.js
> +                        "blocks": blocks,
nit: I think inlining this is better, as blocks is not used elesewhere and this is quite compact this way

```suggestion
                        "blocks": await Slack.buildBlocks(monitorJSON, heartbeatJSON, textMsg, msg),
```

2023-10-13 23:29 UTC, CommanderStorm commented on server/notification-providers/slack.js
> +
```suggestion
```

2023-10-14 11:35 UTC, CommanderStorm approved these changes

2023-10-14 11:50 UTC, chakflying commented
I don't think the functions need to be async? I would prefer if the `baseUrl` is obtained before, and the building functions are left as normal.

2023-10-14 15:28 UTC, septemberservices commented
I've refactored the functions to not be async. Currently, some checks fail but I am confident they have nothing to do with my changes (they seem to have to do with Cypress not being installed)

2023-10-14 15:42 UTC, DaanMeijer commented
I've refactored the functions to not be async. Currently, some checks fail but I am confident they have nothing to do with my changes (they seem to have to do with Cypress not being installed)

2023-10-14 16:42 UTC, chakflying requested changes

2023-10-14 16:42 UTC, chakflying commented on server/notification-providers/slack.js
> +     * @returns {Promise<*[object]>} The rich content blocks for the Slack message
```suggestion
     * @returns {Array<object>} The rich content blocks for the Slack message
```

2023-10-14 16:42 UTC, chakflying commented on server/notification-providers/slack.js
> +                        "blocks": await Slack.buildBlocks(baseURL, monitorJSON, heartbeatJSON, title, msg),
```suggestion
                        "blocks": Slack.buildBlocks(baseURL, monitorJSON, heartbeatJSON, title, msg),
```

2024-02-17 23:41 UTC, CommanderStorm approved these changes

2024-02-26 20:22 UTC, jaknz commented
> Before: ![image](https://private-user-images.githubusercontent.com/35113929/275078891-3f5fd021-ee7f-47f5-818b-71d834203493.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5Nzg3MzQsIm5iZiI6MTcwODk3ODQzNCwicGF0aCI6Ii8zNTExMzkyOS8yNzUwNzg4OTEtM2Y1ZmQwMjEtZWU3Zi00N2Y1LTgxOGItNzFkODM0MjAzNDkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI2VDIwMTM1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkYjRiOGZjNzAwYWRiYjIyODc1YzczOGMzZTUzMzEzODhkYTVlYTQzODFiZTUyZTM0NDY1ZDM2OGRmMWRhOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6B9hI4IvLm7qjsUcdh_ePsw_ZR8tRzjrOlqej1mtHcQ)
> 
> After: ![image](https://private-user-images.githubusercontent.com/35113929/275078734-906eb7dc-def3-4ce5-a429-c87cb94ab7f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5Nzg3MzQsIm5iZiI6MTcwODk3ODQzNCwicGF0aCI6Ii8zNTExMzkyOS8yNzUwNzg3MzQtOTA2ZWI3ZGMtZGVmMy00Y2U1LWE0MjktYzg3Y2I5NGFiN2Y4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI2VDIwMTM1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjODgxOGQ0YTFiNzUwMDY1YWY2NDI4ODIyMWFmNmRlNTU0YTVhNDVlMWJkNWZhODljZWI5ODQ2ZjgwYWM2NTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Yakdk2XMtd_HhxNKjtuQvmOik706juWbLqgK0K0_p4M)

I don't have a URL set for my Kuma instance, because it's running inside a Docker container and I don't want recipients of my Slack notifications to try to click it. Great, so the "Visit Uptime Kuma" button is automatically disabled because of this change: https://github.com/louislam/uptime-kuma/issues/3274

However, this appears to also disable the "Visit site" button, unless I'm mis-reading these commits and the functionality hasn't been rolled into release yet. Could someone clarify please? Ideally the "Visit site" button is visible and works even if there's no Kuma host defined.

2024-02-26 23:06 UTC, CommanderStorm commented
> I'm mis-reading these commits and the functionality hasn't been rolled into release yet

There currently is no `Visit Site` button. This PR contributes it.
Current review/release planning is [`v2.1`](https://github.com/louislam/uptime-kuma/milestone/40)

2024-04-02 00:43 UTC, CommanderStorm commented
Thanks for the change to the notification provider!

All changes in this PR are small and uncontroversial
⇒ pulling out of 2.1 and merging into 2.0 with junior maintainer approval

2024-04-02 00:43 UTC, merged

2024-05-24 11:40 UTC, kmcrawford commented
I see this is merged, do we know when it will be released?

2024-05-24 12:03 UTC, CommanderStorm commented
We have written down what needs to happen before v2.0.0-beta1 can happen in #4500