Add microsoft teams notification provider
louislam/uptime-kuma pull request #395
Opened 2021-09-12 17:57 UTC by WillianRod

## What I've done?
- Added Microsoft Teams notification provider

## Screen captures
![image](https://user-images.githubusercontent.com/6539258/132997738-cc2b9ea3-a91d-4158-a60e-cfa7d5aaa922.png)

#### Test notification
![image](https://user-images.githubusercontent.com/6539258/132997796-142e51e6-4737-4de7-8fcc-e1af6a44e380.png)

#### Down notification
![image](https://user-images.githubusercontent.com/6539258/132997766-2bfaedbc-badf-44b2-9827-cad258929593.png)

#### Up notification
![image](https://user-images.githubusercontent.com/6539258/132997773-96d5b585-4afe-43d3-afd7-4a8b0fa11099.png)

2021-09-12 20:01 UTC, gaby commented
@WillianRod Microsoft Teams is already supported via `apprise` (already preinstalled in the Docker Image).

More information here: https://github.com/caronc/apprise/wiki/Notify_msteams

2021-09-12 20:48 UTC, WillianRod commented
> 
> 
> @WillianRod Microsoft Teams is already supported via `apprise` (already preinstalled in the Docker Image).
> 
> More information here: https://github.com/caronc/apprise/wiki/Notify_msteams

@gabyI know that, but in my use-case (running Uptime Kuma with Caprover) it would be more pratical if teams integration was built in.

Where I work we have a total of 12 teams, my intention is to bring Kuma to be our main monitoring tool. We use Microsoft Teams to chat and each team have its own Microsoft Teams channel.

My intention is to have all teams webhook url seted up and when adding a new monitor url, I just need to select the Microsoft Teams notification for the team responsible for that aplication.

![image](https://user-images.githubusercontent.com/6539258/133002165-323bf6ec-4b85-4c5a-9f68-63cb467c611d.png)

| Application | Team |
| --- | --- |
| Application 01 | Team A |
| Application 02 | Team A |
| Application 03 | Team B |
| Application 04 | Team C |
| Application 05 | Team C |

With Microsoft Teams integration built in I just need to create a webhook url for every new team and add it to Kuma notifications.

2021-09-12 20:49 UTC, MichelBaie commented
I totally agree and would like to do same

2021-09-12 20:55 UTC, gaby commented
> > @WillianRod Microsoft Teams is already supported via `apprise` (already preinstalled in the Docker Image).
> > More information here: [caronc/apprise/wiki/Notify_msteams](https://github.com/caronc/apprise/wiki/Notify_msteams)
> 
> @gaby I know that, but in my use-case (running Uptime Kuma with Caprover) it would be more pratical if teams integration was built in.
> 
> Where I work we have a total of 12 teams, my intention is to bring Kuma to be our main monitoring tool. We use Microsoft Teams to chat and each team have its own Microsoft Teams channel.
> 
> My intention is to have all teams webhook url seted up and when adding a new monitor url, I just need to select the Microsoft Teams notification for the team responsible for that aplication.
> 
> ![image](https://user-images.githubusercontent.com/6539258/133002165-323bf6ec-4b85-4c5a-9f68-63cb467c611d.png)
> 
> Application	Team
> Application 01	Team A
> Application 02	Team A
> Application 03	Team B
> Application 04	Team C
> Application 05	Team C
> With Microsoft Teams integration built in I just need to create a webhook url for every new team and add it to Kuma notifications.

I see what you are trying to do, I just don't see how is that different than creating multiple notifications with apprise? Apprise is already built-in as you said, why should uptime-kuma create its own implementation of a notification already supported.

2021-09-12 20:56 UTC, MichelBaie commented
> > > @WillianRod Microsoft Teams is already supported via `apprise` (already preinstalled in the Docker Image).
> > > More information here: [caronc/apprise/wiki/Notify_msteams](https://github.com/caronc/apprise/wiki/Notify_msteams)
> > 
> > 
> > @gaby I know that, but in my use-case (running Uptime Kuma with Caprover) it would be more pratical if teams integration was built in.
> > Where I work we have a total of 12 teams, my intention is to bring Kuma to be our main monitoring tool. We use Microsoft Teams to chat and each team have its own Microsoft Teams channel.
> > My intention is to have all teams webhook url seted up and when adding a new monitor url, I just need to select the Microsoft Teams notification for the team responsible for that aplication.
> > ![image](https://user-images.githubusercontent.com/6539258/133002165-323bf6ec-4b85-4c5a-9f68-63cb467c611d.png)
> > Application	Team
> > Application 01	Team A
> > Application 02	Team A
> > Application 03	Team B
> > Application 04	Team C
> > Application 05	Team C
> > With Microsoft Teams integration built in I just need to create a webhook url for every new team and add it to Kuma notifications.
> 
> I see what you are trying to do, I just don't see how is that different than creating multiple notifications with apprise? Apprise is already built-in as you said, why should uptime-kuma create its own implementation of a notification already supported.

I just want Microsoft Teams, not other services, why not integrate it directly into uptime-kuma ?
Teams is for professional use, and i think lot peoples are using it

2021-09-12 20:58 UTC, gaby commented
> > > > @WillianRod Microsoft Teams is already supported via `apprise` (already preinstalled in the Docker Image).
> > > > More information here: [caronc/apprise/wiki/Notify_msteams](https://github.com/caronc/apprise/wiki/Notify_msteams)
> > > 
> > > 
> > > @gaby I know that, but in my use-case (running Uptime Kuma with Caprover) it would be more pratical if teams integration was built in.
> > > Where I work we have a total of 12 teams, my intention is to bring Kuma to be our main monitoring tool. We use Microsoft Teams to chat and each team have its own Microsoft Teams channel.
> > > My intention is to have all teams webhook url seted up and when adding a new monitor url, I just need to select the Microsoft Teams notification for the team responsible for that aplication.
> > > ![image](https://user-images.githubusercontent.com/6539258/133002165-323bf6ec-4b85-4c5a-9f68-63cb467c611d.png)
> > > Application	Team
> > > Application 01	Team A
> > > Application 02	Team A
> > > Application 03	Team B
> > > Application 04	Team C
> > > Application 05	Team C
> > > With Microsoft Teams integration built in I just need to create a webhook url for every new team and add it to Kuma notifications.
> > 
> > 
> > I see what you are trying to do, I just don't see how is that different than creating multiple notifications with apprise? Apprise is already built-in as you said, why should uptime-kuma create its own implementation of a notification already supported.
> 
> I just want Microsoft Teams, not other services, why not integrate it directly into uptime-kuma ?
> Teams is for professional use, and i think lot peoples are using it

If you are using Caprover, then you are using the Docker Image. Which means apprise/Microsoft Teams support is already built-in.

2021-09-12 21:05 UTC, gaby commented
👍🏻 Looks good though!

2021-09-12 21:17 UTC, Saibamen requested changes

2021-09-12 21:17 UTC, Saibamen commented on src/components/notifications/Teams.vue
> +            name: "teams",
We can use `name` from `Teams` class

2021-09-13 02:04 UTC, louislam commented
Any existing notifications in Apprise will still be accepted, because Apprise is not available for non-docker users.

Also, native integration is usually faster while sending a notification and it is possible to have a better notification format. While Apprise could only provide a sentence of message.

2021-09-13 12:34 UTC, louislam commented
Is it a paid feature? I cannot find the "App" tab in Microsoft Team

![image](https://user-images.githubusercontent.com/1336778/133084226-1be807c0-fd69-44f5-b23c-aa4ae9f266b4.png)

2021-09-13 12:42 UTC, WillianRod commented
@louislam I think the free version does not allow teams creation. 

![image](https://user-images.githubusercontent.com/6539258/133084738-a166a95d-c2a8-4a4d-85b8-46e38f985fbf.png)

In the bottom I have a button called "Create or join a team" something like that.

I can help you test this implementation. I can create a Webhook URL so you can test.

Do you have somewhere I can send you that?

2021-09-13 14:33 UTC, WillianRod commented
@louislam sent you you a webhook url on your email `info@website.louislam.net`

2021-09-13 16:48 UTC, louislam commented
> @louislam sent you you a webhook url on your email `info@website.louislam.net`

Thanks, but not receive.
Never mind, I found an alumni ms account that enable to create a team in MS Teams.

Tested, UP/DOWN is ok, but general message is not sent.
That means if `heartbeatJSON` is null, it should send the `msg` .

2021-09-13 17:07 UTC, WillianRod commented
@louislam cool, fixed 😄

2021-09-15 08:38 UTC, merged