[empty commit] pull request for Add 'zabbix trigger' monitor
louislam/uptime-kuma pull request #3972
Opened 2023-11-01 23:42 UTC by Hex4919

⚠️⚠️⚠️ Since we do not accept all types of pull requests and do not want to waste your time. Please be sure that you have read pull request rules:
https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md#can-i-create-a-pull-request-for-uptime-kuma

Tick the checkbox if you understand [x]:
- [x ] I have read and understand the pull request rules.

# Description

I want to add a 'Zabbix Trigger' Monitor, which will query the API of a Zabbix Server and get the status of a trigger.

**Why?** I use uptime-kuma as a simple 'customer-side' status page. In the background there is more complex monitoring using Zabbix.   
It would be nice to use the existing data & triggers from zabbix and show them in uptime-kuma, to get the true overview into the status page and not only part of the monitoring.

## Type of change

Please delete any options that are not relevant.

- New feature (non-breaking change which adds functionality)

2023-11-24 07:29 UTC, louislam commented
If I understand it, you meant this monitor will query the Zabbix API in a fixed interval like another monitors do.

If yes, it is OK to be added.

You can add a new monitor type here:
https://github.com/louislam/uptime-kuma/tree/master/server/monitor-types

Here is the tailscale monitor for your reference: 
https://github.com/louislam/uptime-kuma/pull/3178



I am still working on 2.0.0,  this pr may be expected in 2.2.0.

2023-11-27 11:03 UTC, DonovanDiamond commented
Let me know if assistance is needed, this would be incredible for me as I use Zabbix for our admins, and uptime kuma for our customers status pages.

2023-12-01 18:01 UTC, chakflying commented
Please add translation for `en.json` only. Other languages should be added through Weblate.

2024-04-02 01:46 UTC, CommanderStorm requested changes
First sorry for the long review time.
Your PR somewhat got off my radar/never entered it 😅

2024-04-02 01:46 UTC, CommanderStorm commented on server/monitor-types/zabbix-trigger.js
> +                // Will be deprecated, but Bearer Auth is currently not working
What are you meaning when you say "not working"?

Their docs state that Bearer Auth is the preferred option..
https://www.zabbix.com/documentation/current/en/manual/api#by-authorization-header

2024-04-02 01:46 UTC, CommanderStorm commented on server/monitor-types/zabbix-trigger.js
> +                "id": 1
I am a bit unclear about what the `id` field does. They state that it is

> an arbitrary identifier of the request

=> should we set it to a Random id on each request?

2024-04-02 01:46 UTC, CommanderStorm commented on server/monitor-types/zabbix-trigger.js
> +        let trigger = data.result[0];
```suggestion
        // because we only allow one triggerId, at most one result is returned.
        let trigger = data.result[0];
```

2024-04-02 01:46 UTC, CommanderStorm commented on server/monitor-types/zabbix-trigger.js
> +        let trigger = data.result[0];
I think this line misses that the `result` may also not be a monitor, or am I misunderstanding this monitor?

2024-04-02 01:46 UTC, CommanderStorm commented on server/monitor-types/zabbix-trigger.js
> +                    "output": "extend",
Given that we only care about a few outputs here, would this be better?

```
"output": [
    "triggerid",
    "value",
    "description",
    "comments",
]
```

2024-04-02 01:46 UTC, CommanderStorm commented on server/monitor-types/zabbix-trigger.js
> +                    "selectFunctions": "extend",
Seems like `selectFunctions` is only adding extra infos about `functions`, which we don't use.
Am I reading this wrong or can we remove this?

2024-04-02 01:46 UTC, CommanderStorm commented on server/monitor-types/zabbix-trigger.js
> +            Zabbix Trigger Value Mapping
I could not find a reference to this in their docs.
Are there more states that might be interesting?

The value also might be empty (at least it is in one of their examples). Do we have to pay special attention to this case?

2024-04-02 01:46 UTC, CommanderStorm commented on src/pages/EditMonitor.vue
> +                                    <input id="zabbix_instance_url" v-model="monitor.zabbixInstanceUrl" type="text" class="form-control" required />
I think here a placeholder what the url we expect is might be helpfull.

```suggestion
                                    <input id="zabbix_instance_url" v-model="monitor.zabbixInstanceUrl" type="text" class="form-control" placeholder="https://example.com/zabbix/api_jsonrpc.php" required />
```

2024-04-02 01:46 UTC, CommanderStorm commented on src/pages/EditMonitor.vue
> +                                    <input id="zabbix_trigger_id" v-model="monitor.zabbixTriggerId" type="text" class="form-control" required />
I have never used zabbix.
Is it nessesary to add a helptext how to find the triggerid?

2024-04-02 01:46 UTC, CommanderStorm commented on src/pages/EditMonitor.vue
> +                                    <input id="zabbix_auth_token" v-model="monitor.zabbixAuthToken" type="password" class="form-control" required />
Please use `HiddenInput` for such fields instead to communicate to our users that this is a sensitive field ^^

2024-04-02 01:46 UTC, CommanderStorm commented on src/pages/EditMonitor.vue
> +                                    <input id="zabbix_auth_token" v-model="monitor.zabbixAuthToken" type="password" class="form-control" required />
I have never used zabbix.
Is it nessesary to add a helptext how to find the auth token?

2025-02-17 20:22 UTC, closed without merging