Add 30 day availability to status page
louislam/uptime-kuma pull request #4070
Opened 2023-11-20 16:17 UTC by wzrdtales

Currently the status page shows only the 24 hour availability. This is neither what usually is expected, nor it is configurable currently.

rn, this is just a hack, as it is a env var based setting and not something that can be configured in the frontend. But people waiting for https://github.com/louislam/uptime-kuma/issues/1888 might find this helpful.

2023-11-20 17:22 UTC, CommanderStorm requested changes
See https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md#project-styles
⇒ please provide a setting in the frontend, instead of adding a bodge in the `router` ^^

Please also run the linter and don't change the template of the PR description (the checkboxes are there for a reason ^^)

2023-11-20 17:44 UTC, wzrdtales commented
As I wrote, this is ment rather a hack than a contribution yet. And yes I know the PR description is there for a reason. But I have a good reason to delete it when I write a custom explanation.

All you wrote I already mentioned. This is a fast way to get the functionality, that should be there (b/c on a status page a 24 hour availability is really weird...). So PR'ing this already is for the community, who can take it until this is solved for good. Working on it for real may be on the agenda soon, just not now.

2023-11-21 17:43 UTC, MrRR0112 approved these changes

2024-04-02 02:04 UTC, CommanderStorm commented
> this is ment rather a hack than a contribution

I am going to close this PR as I don't see this PR getting merged in this state.

2024-04-02 02:04 UTC, closed without merging

2024-06-13 06:17 UTC, joebnb commented
i also think 24 hours are too short，would implement this features by official

2024-06-14 01:23 UTC, CommanderStorm commented
@joebnb
Please refer to https://github.com/louislam/uptime-kuma/issues/1888#issuecomment-2068191172 for the status on the issue and how to get involved in this effort ^^