Add monitor for Zookeeper
louislam/uptime-kuma pull request #4114
Opened 2023-11-28 15:29 UTC by AayuStark007

⚠️⚠️⚠️ Since we do not accept all types of pull requests and do not want to waste your time. Please be sure that you have read pull request rules:
https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md#can-i-create-a-pull-request-for-uptime-kuma

Tick the checkbox if you understand [x]:
- [x] I have read and understand the pull request rules.

# Description
I have some zookeeper hosts that I want to monitor. So, I decided to use uptime-kuma, but it does not have a dedicated monitor for zookeeper instances. This PR adds that support by using `zookeeper` client to attempt to establish a connection. Successful connection establishment indicates that the host is up.

PS: I tried using TCP, but it always gives a UP status if the instance is running, but the zookeeper process is down. Hence the need for this monitor.

Fixes #(issue)

## Type of change

- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I ran ESLint and other linters for modified files
- [ ] I have performed a self-review of my own code and tested it
- [ ] I have commented my code, particularly in hard-to-understand areas (including JSDoc for methods)
- [ ] My changes generates no new warnings
- [ ] My code needed automated testing. I have added them (this is optional task)

## Screenshots (if any)

Please do not use any external image service. Instead, just paste in or drag and drop the image here, and it will be uploaded automatically.

2023-11-29 11:04 UTC, louislam commented
It will be accepted, but currently we are working on 2.0.0 and there are a lot of pull requests that are waiting for review. 

It may take some to be merge. Maybe in 2.2.0.

You can check the current progress here:
https://github.com/louislam/uptime-kuma/milestones

2023-11-29 12:31 UTC, AayuStark007 commented
Sure, I can wait for the 2.2.0 release. I have already implemented the feature for my use case, and I wanted to contribute them back to the main project.
So, proceeding from here, do I:
- push my changes to this PR? or raise one separately
- should I add all the code as part of a single PR, or is it better to have frontend and backend changes as separate PRs?

2023-11-30 00:35 UTC, louislam commented
Put it here and a single PR is preferred, so that we don't need to checkout two PRs in order to test it.

2023-11-30 19:32 UTC, louislam commented
Please note that it cannot pass the ARM64 test, probably due to native build issue.

You may need to find another library or find a way to pre-build that.

2023-12-01 13:27 UTC, AayuStark007 commented
I realized I could simply use the inbuilt `node:net` module to do the same. This will remove any dependency on 3rd party library.

2024-05-19 22:35 UTC, CommanderStorm requested changes
I have gone trough this monitor and have left inline comments where things need to be changed ^^

2024-05-19 22:35 UTC, CommanderStorm commented on db/knex_migrations/2023-11-28-2022-add-zookeeper-column.js
> +        table.string("zookeeper_host", 255);
Please use the `hostname` and `timeout` fields instead.
I don't see a reason why we shoud add these fields ^^

2024-05-19 22:35 UTC, CommanderStorm commented on server/model/monitor.js
> +                } else if (this.type === "zookeeper") {
We have recently started using a better syntax for creating monitors.
It is documented in our contribution guide here:
https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md#:~:text=new%20monitoring%20types

The currently migrated montiors live here:
https://github.com/louislam/uptime-kuma/tree/master/server/monitor-types

All new monitors MUST to use this, to use this format instead.
Rationale: We can't keep dumping all code in the giormous `monitor.js`. This does not scale in terms of maintenance/.. effort.

2024-05-19 22:35 UTC, CommanderStorm commented on src/pages/EditMonitor.vue
> +                                    <input id="zookeeperHost" v-model="monitor.zookeeperHost" type="text" class="form-control" required>
Please include a helptext about what you mentioned in the PR-description.
Currently, a user might just think it is not working, right?

2024-05-19 22:36 UTC, CommanderStorm commented on src/lang/en.json
> +    "Zookeeper Timeout": "Zookeeper Connect Timeout (ms)"
typo introduced by a merge

```suggestion
    "Zookeeper Timeout": "Zookeeper Connect Timeout (ms)",
```

2024-05-19 22:43 UTC, CommanderStorm commented on server/model/monitor.js
> +    redisPingAsync, mongodbPing, kafkaProducerAsync, getOidcTokenClientCredentials, rootCertificatesFingerprints, axiosAbortSignal, zookeeperConnect
another merge-typo

```suggestion
    redisPingAsync, kafkaProducerAsync, getOidcTokenClientCredentials, rootCertificatesFingerprints, axiosAbortSignal, zookeeperConnect
```

2025-03-25 01:31 UTC, CommanderStorm commented
I am going to close this PR as it has become stale for a longer time with no movement in sight.
If you would like to make zookeeper a reality as an monitor, we would be open to that assuming under the current `MonitoringType` impl and with testcases.

2025-03-25 01:31 UTC, closed without merging