Hevans/add heii on call notification provider
louislam/uptime-kuma pull request #4485
Opened 2024-02-13 02:13 UTC by hevans66

Tick the checkbox if you understand [x]:
- [x] I have read and understand the pull request rules.

Add notification provider for [Heii On-Call](https://heiioncall.com/).

## Type of change

Please delete any options that are not relevant.

- New feature (non-breaking change which adds functionality)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I ran ESLint and other linters for modified files
- [x] I have performed a self-review of my own code and tested it
- [x] I have commented my code, particularly in hard-to-understand areas (including JSDoc for methods)
- [x] My changes generates no new warnings
- [ ] My code needed automated testing. I have added them (this is optional task)

## Screenshots (if any)

<img width="1349" alt="image" src="https://github.com/louislam/uptime-kuma/assets/587984/c1dc4f2a-d539-4320-a913-220cf104283d">

<img width="498" alt="image" src="https://github.com/louislam/uptime-kuma/assets/587984/1214e5de-062e-4afe-817c-e5322ac106e3">

2024-02-13 10:48 UTC, CommanderStorm requested changes
Mostly, this is looking good.
I have left some inline remarks about UX and code-quality.

Please attach screenshots of the 3 types of events `DOWN`/`UP`, `Certificate Expiry`[^1] and `Testing` to the description.
(we should really document this one in the contribution guide...)

[^1]: See https://badssl.com/ for broken certs

2024-02-14 00:58 UTC, hevans66 commented on src/components/notifications/HeiiOnCall.vue
> +        <label for="heiioncall-trigger-id" class="form-label">{{ $t("Trigger ID") }}<span
Not a stupid question at all. I feel like this is one of those that can go either way. I suppose in this context we are using Trigger as basically a proper noun. I'll remove the tranlation.

2024-02-14 01:39 UTC, hevans66 commented on server/notification-providers/heii-oncall.js
> +        if (!heartbeatJSON) {
I believe my changes do what you asked for. Resolving this comment, but let me know if what I did missed the mark.

2024-02-14 01:50 UTC, hevans66 commented on src/components/notifications/HeiiOnCall.vue
> +            <a href="https://heiioncall.com/docs" target="_blank">Heii On-Call Documentation</a>
Trigger ID is very front and center as soon you create a trigger in Heii On-Call. It is mentioned in many places on Manual Trigger type documentation. I don't think there will be any confusion as to where to grab that from. If you would like I can add more text here to be explicit about how to find the Trigger ID, but I figured we wanted to keep the Setup Notification screen as clean as possible.

2024-02-14 01:51 UTC, hevans66 commented
@CommanderStorm Thanks for the review. I believe I have addressed all your concerns.

2024-02-14 22:05 UTC, CommanderStorm commented on src/components/notifications/HeiiOnCall.vue
> +            <a href="https://heiioncall.com/docs" target="_blank">Heii On-Call Documentation</a>
As long as how would be clear to a new user of said software, this is fine by me ^^

2024-02-14 22:36 UTC, CommanderStorm commented on server/notification-providers/heii-oncall.js
> +    }
This should refactor the code to be closer to what the other notification providers look like => keeping it more consistent.

```suggestion
    async send(notification, msg, monitorJSON = null, heartbeatJSON = null) {
        const okMsg = "Sent Successfully.";
        const payload = heartbeatJSON || {};

        const baseURL = await setting("primaryBaseURL");
        if (baseURL && monitorJSON) {
            payload["url"] = baseURL + getMonitorRelativeURL(monitorJSON.id);
        }

        const config = {
            headers: {
                Accept: "application/json",
                "Content-Type": "application/json",
                Authorization: "Bearer " + notification.heiiOnCallApiKey,
            },
        };
        
        const heiiUrl = `https://heiioncall.com/triggers/${notification.heiiOnCallTriggerId}/`;
        
        // docs https://heiioncall.com/docs#manual-triggers
        try {
            if (!heartbeatJSON) {
                // Testing or general notification like certificate expiry
                payload["msg"] = msg;
                await axios.post(heiiUrl + "alert", payload, config);
                return okMsg;
            }

            if (heartbeatJSON.status === DOWN) {
                await axios.post(heiiUrl + "alert", payload, config);
                return okMsg;
            }
            if (heartbeatJSON.status === UP) {
                await axios.post(heiiUrl + "resolve",payload, config);
                return okMsg;
            }
        } catch (error) {
            this.throwGeneralAxiosError(error);
        }
    }
```

2024-02-14 22:41 UTC, CommanderStorm commented on src/components/notifications/HeiiOnCall.vue
> +        <a href="https://heiioncall.com/docs" target="_blank">{{ $t("documentationOf", ["Heii On-Call"]) }}</a>
I think adding translations in this way might be easier for our translators

```suggestion
        <template #documentation>
            <a href="https://heiioncall.com/docs" target="_blank">{{ $t("documentationOf", ["Heii On-Call"]) }}</a>
        </template>
```

2024-02-14 22:41 UTC, CommanderStorm commented on src/lang/en.json
> +    "wayToGetHeiiOnCallDetails": "How to get the Tigger ID and API Keys is explained in the {0}",
```suggestion
    "wayToGetHeiiOnCallDetails": "How to get the Tigger ID and API Keys is explained in the {documentation}",
```

2024-02-14 22:43 UTC, CommanderStorm commented on src/components/notifications/HeiiOnCall.vue
> +            <a href="https://heiioncall.com/docs" target="_blank">Heii On-Call Documentation</a>
resolving this one, as below is better to track this (below has the fixed indentation ^^)

2024-02-14 22:45 UTC, CommanderStorm reviewed
formatting issues introduced in above fix

2024-02-14 22:45 UTC, CommanderStorm commented on server/notification-providers/heii-oncall.js
> +
```suggestion

```

2024-02-14 22:45 UTC, CommanderStorm commented on server/notification-providers/heii-oncall.js
> +
```suggestion

```

2024-02-14 22:45 UTC, CommanderStorm commented on server/notification-providers/heii-oncall.js
> +                await axios.post(heiiUrl + "resolve",payload, config);
```suggestion
                await axios.post(heiiUrl + "resolve", payload, config);
```

2024-02-14 22:51 UTC, CommanderStorm approved these changes
Okay, I changed the formatting of the code a bit to be closer to the other notification providers.
Could you review the changes I added in https://github.com/louislam/uptime-kuma/pull/4485/commits/cc000117ca9b8f888c69a31b9c8f2841b79bab7f?

Other than that, I am happy with the current code.

I am unsure if we should change the translations in this context as suggested in https://github.com/louislam/uptime-kuma/pull/4485#pullrequestreview-1881439791 => I am going to leave this up to you to either accept/resolve

2024-02-16 22:31 UTC, hevans66 commented
@CommanderStorm awesome! Accepted your changes. Thanks so much for the review.

2024-03-04 22:55 UTC, hevans66 commented
@CommanderStorm let me know if there is anything else I can do to help this get merged. I'd like to work on a guide for setting up Uptime Kuma with Heii On-Call, and would like to have this in before its published.

2024-03-11 10:14 UTC, CommanderStorm commented
Actually there is: 
I missed in the previous review that this is missing the screenshot from the `Testing` state (the "Test"-button in above screenshot)

Other than that I would be happy to merge this into the upcoming v2.0 release.

2024-03-11 17:57 UTC, hevans66 commented
Testing screenshot has been added.

2024-03-11 19:51 UTC, CommanderStorm commented
Thanks for the notification provider!
I think adding it is uncontroversial as it matches the code style and the appropriate tests have been performed.
⇒ merging with junior maintainer approval.

2024-03-11 19:51 UTC, merged