Add WPush Notification Provider
louislam/uptime-kuma pull request #4603
Opened 2024-03-20 11:09 UTC by anhao

⚠️⚠️⚠️ Since we do not accept all types of pull requests and do not want to waste your time. Please be sure that you have read pull request rules:
https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md#can-i-create-a-pull-request-for-uptime-kuma

Tick the checkbox if you understand [x]:
- [x] I have read and understand the pull request rules.

# Description

 Add WPush Notification Provider 

## Type of change

Please delete any options that are not relevant.

- New feature (non-breaking change which adds functionality)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I ran ESLint and other linters for modified files
- [x] I have performed a self-review of my own code and tested it
- [x] I have commented my code, particularly in hard-to-understand areas (including JSDoc for methods)
- [x] My changes generates no new warnings
- [x] My code needed automated testing. I have added them (this is optional task)

## Screenshots (if any)

![image](https://github.com/louislam/uptime-kuma/assets/9844218/fb0e3476-11aa-4fbd-bbd1-afe28b70a95f)

2024-03-20 13:17 UTC, chakflying commented on server/notification-providers/wpush.js
> +                return ret.data.message;
If this is an error condition, maybe we should do `throw new Error(ret.data.message)` instead.

2024-03-20 13:23 UTC, CommanderStorm requested changes
Overall, this looks good.
I have left some inline comments below.

I have added a table to the PR-description. Could you fill it with the requisite screnshots?

[Explanation on the second one](https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md):
> Offering notifications is close to the core of what we are as an uptime monitor. Therefore, making sure that they work is also really important. Because testing notification providers is quite time intensive, we mostly offload this onto the person contributing a notification provider.
> 
> To make shure you have tested the notification provider, please include screenshots of the following events in the pull-request description:
> 
> - `UP`/`DOWN`
> - Certificate Expiry via https://expired.badssl.com/
> - Testing (the test button on the notification provider setup page)

2024-03-20 13:23 UTC, CommanderStorm commented on server/notification-providers/wpush.js
> +    checkStatus(heartbeatJSON, monitorJSON) {
I think `checkStatus` does not really give an accurate meaning what this function does. What do you think about this instead?

```suggestion
    generateTitle(heartbeatJSON, monitorJSON) {
```

2024-03-21 05:25 UTC, anhao commented on src/components/notifications/WPush.vue
> +        <label for="wpush-channel" class="form-label">发送通道</label>
Think , Detailed channel descriptions can be viewed at the link below

![image](https://github.com/louislam/uptime-kuma/assets/9844218/c80cb873-b25d-4f02-9db4-8e81228f2386)

2024-05-19 18:24 UTC, CommanderStorm requested changes
Please refer to above review. I think you missed this paragraph:

> I have added a table to the PR-description. Could you fill it with the requisite screnshots?
> 
> [Explanation on the second one](https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md):
> > Offering notifications is close to the core of what we are as an uptime monitor. Therefore, making sure that they work is also really important. Because testing notification providers is quite time intensive, we mostly offload this onto the person contributing a notification provider.
> > 
> > To make shure you have tested the notification provider, please include screenshots of the following events in the pull-request description:
> > 
> > - `UP`/`DOWN`
> > - Certificate Expiry via https://expired.badssl.com/
> > - Testing (the test button on the notification provider setup page)

2024-08-09 23:07 UTC, CommanderStorm commented
@anhao Thanks for the PR.
Given that you have not responded since May, I am going to close this PR.
We can reopen the PR if you resolve the merge conflicts and provide the requested screenshots as proof that this notification provider works.
Hope you understand 😅

2024-08-09 23:07 UTC, closed without merging

2024-08-26 01:43 UTC, anhao commented
@CommanderStorm  
Thanks, I have pushed a new PR  https://github.com/louislam/uptime-kuma/pull/5049