feat: Datadog type monitor
louislam/uptime-kuma pull request #4616
Opened 2024-03-24 19:27 UTC by seluard

⚠️⚠️⚠️ Since we do not accept all types of pull requests and do not want to waste your time. Please be sure that you have read pull request rules:
https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md#can-i-create-a-pull-request-for-uptime-kuma

Tick the checkbox if you understand [x]:
- [x] I have read and understand the pull request rules.

# Description

Hello @louislam ! 

Some context:
We use DataDog to monitor our stack/services, and it does not offer status page product, we take a look at the open sources projects that could fit. We found uptime-kuma 💘  the one we like the most and could fit better. 

We even work already into a POC, but we need to work around with a way to get DataDog monitor states into uptime-kuma, creating push monitors and an extra service that should be the one that gather datadog and make the request to the push monitor endpoint. 

Instead of having this kind of workaround, I thought that could be fun and worth to contribute to the project! (Alert! : I'm not a developer, so please bear with me and my small code changes).

With this feature, either us or anyone that is using DataDog will be able to use uptime-kuma out of the box to create status pages.

## New DataDog type monitor

This feature will allow to sync DataDog monitor state with uptime-kuma monitor.

As this is just initial base code changes, there are some things still need to be added:
- [ ] Tests
- [ ] Translation in place
- [ ] BUG: The creation works, but I missed something cause updating the monitor fields that I added is not working (Again bear with me 😞 )
- [ ] Documentation about this new monitor type
- [ ] Go through the checklist properly 
- [ ] datadog-api-cli dependency or use just http to keep uptime-kuma dependencies lean and clean.

## Type of change

- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I ran ESLint and other linters for modified files
- [ ] I have performed a self-review of my own code and tested it
- [ ] I have commented my code, particularly in hard-to-understand areas (including JSDoc for methods)
- [ ] My changes generates no new warnings
- [ ] My code needed automated testing. I have added them (this is optional task)

## Screenshots 

![Screenshot 2024-03-24 at 20 00 25](https://github.com/louislam/uptime-kuma/assets/22504202/64e7978d-b8ca-43db-883d-b1caacede9f9)

2024-05-23 13:35 UTC, CommanderStorm requested changes

2024-05-23 13:35 UTC, CommanderStorm commented on db/knex_migrations/2024-03-24-0000-add-datadog-monitor-type.js
> +            table.string("datadog_site", 255);
please use the existing hostname field, as this acts similar enough.

2024-05-23 13:35 UTC, CommanderStorm commented on db/knex_migrations/2024-03-24-0000-add-datadog-monitor-type.js
> +            table.string("datadog_app_key", 255);
Is one of these a password? If yes this could use the existing Rename `radiusPassword` (has to be renamed to monitor.password for general use) field

2024-05-23 13:58 UTC, CommanderStorm commented
@chakflying @louislam @Saibamen @Zaid-maker 

Currently, we offer pretty basic monitors (grpc, http, dns, docker, databases).
I think this monitor does not fit into the line of moniotors we currently offer.

Similar as in https://github.com/louislam/uptime-kuma/pull/4619, I think that limiting our scope a bit is nessesary in this area.
I think including such monitors via https://github.com/louislam/uptime-kuma/issues/1117 instead might be a better call..

What are other peoples oppinions?

2024-05-23 14:03 UTC, Zaid-maker commented
Yes I agree with you!

We need to limit our current ecosystem with limit amount of monitors, also maybe in feature we can add these feature as a Premium feature or smh like that

2024-05-24 07:38 UTC, Saibamen commented
These 3rd party monitors are hard to maintain, because only our users are checking changelogs for APIs etc.

The best solution will be to have plugins system.

2024-08-21 22:44 UTC, CommanderStorm commented
> These 3rd party monitors are hard to maintain, because only our users are checking changelogs for APIs etc.

Hi @seluard Thanks for your work, but I don't think this fits into the scope that we can currently support given the engineering that is going into the project. Sorry

2024-08-21 22:44 UTC, closed without merging