fix: Update `axios`, `axios-ntlm`, `@actions/github` and `dompurify`  [1.23.X]
louislam/uptime-kuma pull request #4652
Opened 2024-04-04 16:20 UTC by Saibamen

`11 vulnerabilities (1 low, 4 moderate, 5 high, 1 critical)`

instead of

`14 vulnerabilities (1 low, 7 moderate, 5 high, 1 critical)`

Replaces PR https://github.com/louislam/uptime-kuma/pull/4647

Other vulnerabilities could be fixed by simply deleting `package-lock.json` and doing `npm update`, but this is too much for PR. This done by @louislam many times in the past...

Vite should be updated to `4.5.3` to fix `fs.deny` high vulnerability (7.5/10 CVSS score).

2024-04-04 17:03 UTC, CommanderStorm requested changes
I don't quite get why https://github.com/louislam/uptime-kuma/pull/4647 was closed, anyway.

These are the relevant parts of https://github.com/louislam/uptime-kuma/pull/4647#pullrequestreview-1978218721

2024-04-04 21:34 UTC, Saibamen commented on package.json
> +        "axios": "~0.28.1",
This is diff: https://www.diffchecker.com/bIToqvVl/

It is better - added stack trace and `cause`

2024-04-04 23:54 UTC, Zaid-maker commented
> simply deleting package-lock.json

What u mean by deleting `package-lock.json`??

2024-04-05 03:47 UTC, merged

2024-04-05 08:03 UTC, Saibamen commented
> What u mean by deleting `package-lock.json`??

`del package-lock.json` and `npm install` to recreate `package-lock.json` file with latest packages in version ranges from `package.json`

2024-04-05 14:33 UTC, Zaid-maker commented
> > What u mean by deleting `package-lock.json`??
> 
> `del package-lock.json` and `npm install` to recreate `package-lock.json` file with latest packages in version ranges from `package.json`

Ohh for recreating got it