GH-5214: feat: Add Docker service availability monitoring
louislam/uptime-kuma pull request #5215
Opened 2024-10-18 05:14 UTC by SheepReaper

⚠️⚠️⚠️ Since we do not accept all types of pull requests and do not want to waste your time. Please be sure that you have read pull request rules:
https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md#can-i-create-a-pull-request-for-uptime-kuma

Tick the checkbox if you understand [x]:
- [x] I have read and understand the pull request rules.

# Description

Introduces Docker service availability to monitor uptime and status of Docker services alongside existing types. Updates the database schema to support "docker_service". Enhances the user interface to allow configuration of Docker service parameters within the monitor setup.

This change allows for more granular monitoring capabilities by checking the running state of services in a Docker environment.

Relates to implementing extended Docker monitoring functionalities.

implements #5214

## Type of change

- User interface (UI)
- New feature (non-breaking change which adds functionality)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I ran ESLint and other linters for modified files
- [x] I have performed a self-review of my own code and tested it
- [x] I have commented my code, particularly in hard-to-understand areas (including JSDoc for methods)
- [x] My changes generates no new warnings
- [ ] My code needed automated testing. I have added them (this is optional task)

## Screenshots (if any)
<img width="1372" alt="image" src="https://github.com/user-attachments/assets/0b80e418-84bb-468c-97aa-d3b94abbef0b">
<img width="1372" alt="image" src="https://github.com/user-attachments/assets/76ba378c-e7a0-4a65-aabf-47c966c9fed6">

@louislam

2024-10-20 14:59 UTC, CommanderStorm requested changes
Lets go back one step to the conceptual level how this should be done:

We are currently in the migration towards a few things that are relevant for this PR:
- we are migrating from the ginormous `monior.js` to more maintainable monitoring types. See [reddis](https://github.com/louislam/uptime-kuma/pull/4393) for a similar PR.
  => This PR needs to use the newer variant.
- having two really close monitors is not ideal for users. Please merge this with the docker monitor unless there is a reason this should not happen
- For monitors, we need testcases (f.ex. via testcontainers) to prevent stupid regressions in the future. If this is not possible, that is another story, but I think it likely is => we should try to do so.
  See https://github.com/louislam/uptime-kuma/pull/5199 for a PR on how to use testcontainers
- Please have a look at [this file](https://github.com/simshaun/uptime-kuma/blob/6671a97028b2240d8626ae2966fe54313e5ea442/server/monitor-types/dns.js) and check if the newer conditional approach can work for this monitor

I have changed this to a draft to communicate the early stage of the PR to others better. Feel free to change once this fits better. ^^
If you have any trouble with one of the comments above, feel free to comment.

2024-10-20 16:49 UTC, SheepReaper commented
forgot tag: @CommanderStorm

2024-10-20 17:56 UTC, CommanderStorm commented
> Am I being asked to perform said refactor?

Yes, please migrate to the newer monitoring type structure.
Adding new features to the unmaintainable pile is not workable.

> It's fundamentally a different concept

For you it might, I don't think it is for other users.
To name similarities, Oauth2 vs no auth are both inside of the http monitor.

If you look at [this file](https://github.com/simshaun/uptime-kuma/blob/6671a97028b2240d8626ae2966fe54313e5ea442/server/monitor-types/dns.js), I think we can have a much nicer experience with a bit more effort ^^

> doesn't seem to indicate that a "docker" container exists

For checking if the docker monitor can monitor docker containers (spawned via a testcontaier), there also does not need to be one.
Not sure if what I have in mind fully works => feel free to point out if it does not ^^

> I can instead achieve the tests you're asking for by just mocking the axios responses

That is an alternative, but lets

2024-12-02 09:45 UTC, dylnmatthewswork commented
@SheepReaper @CommanderStorm 

I would really love this feature, it would be good if container hashes change

2024-12-03 00:00 UTC, SheepReaper commented
I'm still tracking this, but I haven't had time lately to do the refactor. I'm happy to do it, but I won't feel bad if someone beats me to it. I just need to find the time.

2025-07-20 19:57 UTC, sadrian80 commented
Any chance this will get implemented?
Monitoring services on Docker Swarm would be really helpful.

2025-08-05 09:02 UTC, codedoga commented
+1 

will this be implemented?

2025-08-25 18:43 UTC, SheepReaper commented
> +1
> 
> will this be implemented?

My initial implementation was/is still good to go as is. I have not even looked at the refactoring that the maintainer requested. If someone else can accomplish that, I don't expect I'll get to it any time soon.

2025-08-25 22:14 UTC, CommanderStorm commented
lets close the PR, we can reopen if this changes or if someone else adopts it 😉

2025-08-25 22:14 UTC, closed without merging