Added Pumble Notification
louislam/uptime-kuma pull request #5342
Opened 2024-11-13 17:38 UTC by cs-jako

⚠️⚠️⚠️ Since we do not accept all types of pull requests and do not want to waste your time. Please be sure that you have read pull request rules:
https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md#can-i-create-a-pull-request-for-uptime-kuma

Tick the checkbox if you understand [x]:
- [x] I have read and understand the pull request rules.

# Description

Notification Provider for Pumble (similar to Slack)

## Type of change

Please delete any options that are not relevant.

- New feature (non-breaking change which adds functionality): Notification Provider

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I ran ESLint and other linters for modified files
- [x] I have performed a self-review of my own code and tested it
- [x] I have commented my code, particularly in hard-to-understand areas (including JSDoc for methods)
- [x] My changes generates no new warnings
- [ ] My code needed automated testing. I have added them (this is optional task)

## Screenshots

| Event             | Screenshot                                                                                           |
|-------------------|------------------------------------------------------------------------------------------------------|
| `UP`              | ![UP](https://github.com/user-attachments/assets/232ce1f0-cd32-4e01-9b32-6c3dc3a00091)               |
| `DOWN`            | ![DOWN](https://github.com/user-attachments/assets/1ccc8543-9d6f-4e5d-802d-2077f8a29e68)             |
| Certificate-expiry| ![Certificate Expiry](https://github.com/user-attachments/assets/a7963aff-c61c-4514-a0e5-b38dca7d9adb)|
| Testing           | ![Testing](https://github.com/user-attachments/assets/9cde1072-46ad-4390-b55b-25fe3d1439a4)          |

2024-11-15 23:21 UTC, CommanderStorm requested changes
Overall, this looks good.
I have left a few changes below. Mostly, could you clairify in a helptext where the webhook url can be found.

2024-11-15 23:21 UTC, CommanderStorm commented on server/notification-providers/pumble.js
> +                await axios.post(webhookUrl, data);
```suggestion
                await axios.post(notification.webhookURL, data);
```

2024-11-16 08:04 UTC, cs-jako commented on server/notification-providers/pumble.js
> +                            "title": "Test Alert",
To my surprise it did during testing. I assumed there was a change in the past

2024-11-16 08:54 UTC, cs-jako commented on server/notification-providers/pumble.js
> +                            "title": "Test Alert",
I'll mark this as resolved for now. If you want me to check for it like it's explained in the docs (heartbeatJSON null) I'll add it.

2024-12-15 12:26 UTC, cs-jako commented
@CommanderStorm I finally had the time to get back to this project. I'm a bit confused about the Review regarding certificate expiry, so I've done some testing. When using expired.badssl.com heartbeatjson and monitorjson are **not** null and the service is considered as down. This is what I assume is expected behaviour according to the documentation.

I currently have a website where the certificate is about to expire in 21 days, awesome for testing. When adding an alert for that website with certificate expiry alert this is what I get:

```
MonitorJson
null
-----
HeartbeatJson:
null
-----
Msg: [Certificate expiry soon][<website>] server certificate <website> will be expired in 21 days
```

Which would trigger the test alert. But according to the documentation only heartbeatJSON is supposed to be null.
If I'm doing something wrong please let me know, otherwise please advise on how to proceed.

2024-12-15 12:30 UTC, cs-jako commented
^ issue still persists after syncing fork with upstream

2025-04-15 07:20 UTC, closed without merging

2025-04-15 15:27 UTC, CommanderStorm commented
@cs-jako sorry, did not apparently get back to you in time. We could remove the Test part of the message => make it into a general message and merge it into v2.1.

2025-04-16 09:05 UTC, cs-jako commented
Hey @CommanderStorm, Thanks for getting back to me. I reopened this in https://github.com/louislam/uptime-kuma/pull/5781