Add fallback text
louislam/uptime-kuma pull request #5476
Opened 2024-12-25 22:45 UTC by elliotmatson

⚠️⚠️⚠️ Since we do not accept all types of pull requests and do not want to waste your time. Please be sure that you have read pull request rules:
https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md#can-i-create-a-pull-request-for-uptime-kuma

Tick the checkbox if you understand [x]:
- [x] I have read and understand the pull request rules.

# Description

Adding fallback text to use in notifications and platforms that don't support cards, otherwise the notification just says "Uptime Kuma sent an attachment"

## Type of change

Please delete any options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- User interface (UI)
- New feature (non-breaking change which adds functionality)
- Breaking change (a fix or feature that would cause existing functionality to not work as expected)
- Other
- This change requires a documentation update

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] I ran ESLint and other linters for modified files
- [x] I have performed a self-review of my own code and tested it
- [x] I have commented my code, particularly in hard-to-understand areas (including JSDoc for methods)
- [ ] My changes generates no new warnings
- [ ] My code needed automated testing. I have added them (this is optional task)

## Screenshots (if any)

Please do not use any external image service. Instead, just paste in or drag and drop the image here, and it will be uploaded automatically.

2025-01-24 08:18 UTC, CommanderStorm requested changes

2025-01-24 08:18 UTC, CommanderStorm commented on server/notification-providers/google-chat.js
> +                fallbackText: chatHeader["title"],
This currently means that the fallback text is just "uptime Kuma alert".
Let's also include what we are notifying to in the notification, or am I missing something?

2025-01-24 16:20 UTC, elliotmatson commented on server/notification-providers/google-chat.js
> +                fallbackText: chatHeader["title"],
That's the default, I forgot why I did that exactly, I think to handle the test notifications that don't pass a value for heatbeatJSON or monitorJSON. If you look at lines 22-27 its overwritten if the values exist by something like this: "✅ SW Auditorium - ATEM Production Studio 2M/E is back online"

2025-01-24 16:21 UTC, elliotmatson commented on server/notification-providers/google-chat.js
> +                fallbackText: chatHeader["title"],
We could also just make it ${msg} if you prefer that

2025-01-24 16:52 UTC, CommanderStorm commented on server/notification-providers/google-chat.js
> +                fallbackText: chatHeader["title"],
Ups. did not notice this while reviewing in the tram this morning
sorry

2025-01-24 16:52 UTC, CommanderStorm approved these changes

2025-01-24 17:11 UTC, elliotmatson commented on server/notification-providers/google-chat.js
> +                fallbackText: chatHeader["title"],
No worries at all!

2025-01-24 17:49 UTC, merged

2025-04-01 07:50 UTC, Erikel746 commented
I think the google chat popup is even more broken now. 
Now the popup doesn't show any Status of the Monitor.
![Screenshot_20250401_094810_One](https://github.com/user-attachments/assets/2578081e-f4fa-4746-8e28-34363bc589fa)

2025-04-01 08:32 UTC, CommanderStorm commented
Just to be sure: you are running beta2?

Otherwise no clue why Google is not using this field. Would be happy if a non-maintainer could have a look. I don't use Google chat and debugging notification providers scales badly.

2025-04-01 09:14 UTC, Erikel746 commented
> Just to be sure: you are running beta2?
> 
> Otherwise no clue why Google is not using this field. Would be happy if a non-maintainer could have a look. I don't use Google chat and debugging notification providers scales badly.

![image](https://github.com/user-attachments/assets/c82655fb-ad7b-4ddc-9faf-447021520b28)
Yes version is beta2.

The card's in the chat are working perfectly its just the popup again.

2025-04-01 11:05 UTC, elliotmatson commented
What device/OS is this on? Beta 2 seems to be working well on my iOS device, but maybe different clients use the fields differently?

2025-04-01 15:56 UTC, Erikel746 commented
> What device/OS is this on? Beta 2 seems to be working well on my iOS device, but maybe different clients use the fields differently?

The OS from the screenshot is android
I just tried it again with ios and it works. I also think that the gmail app in Android handles messages differently.

2025-04-01 16:36 UTC, elliotmatson commented
Of course it does 🫠. Let me see if I still have an old android to test on, and see if I can figure out what fields it's using

2025-04-01 19:30 UTC, Erikel746 commented
I tested the official google documentation example with the chat and gmail app. Both does not work correctly with cardsV2.
First Screenshot is cardsV2 with google documentation example 
 
top: gmail app
bottom: chat app
![WhatsApp Image 2025-04-01 at 21 25 08](https://github.com/user-attachments/assets/2819362e-e57b-4030-b093-97f1b2d21844)

Second Screenshot is cardV1 
top: gmail app
bottom: chat app
![image](https://github.com/user-attachments/assets/a80dc53d-10de-4dee-b8c4-fab56961d70e)

I think the cardsV2 integration from google itself is just broken in the Android apps...

2025-04-01 20:13 UTC, Erikel746 commented
I think I have found the issue. According to the google documentaion for cardsV2 there is no fallbackText that is currently used.

In the Android apps only text is displayed in the popup that is defined in text:” ”. Not the cards content itself

2025-04-01 20:28 UTC, elliotmatson commented
The fallbackText field is at the same level as the cardsV2 object, so that makes sense. It is included in the docs as part of the message object here though: https://developers.google.com/workspace/chat/api/reference/rest/v1/spaces.messages

It looks like this is being tracked here, but its been dead for a few years:
https://issuetracker.google.com/issues/283746283

2025-04-01 20:44 UTC, Erikel746 commented
ah ok. I just saw your comment on the google issue. The assigned developer also replied quite quickly 😅

2025-04-02 00:51 UTC, CommanderStorm commented
> In the Android apps only text is displayed in the popup that is defined outside cardsv2 with text:” ”. Not the cards content itself

Can we just set a text here and make android happy as well?

In any case: we cannot make anybody happy.
If it works for some that would be an improvement to this working for none.
=> if we can fix it, we should. If not 🤷🏻‍♂️

2025-04-02 01:32 UTC, elliotmatson commented
I tested that, and unfortunately on web and iOS that's interpreted as 2 messages, one for the card, and one for the text. So at this point reverting to straight text would probably be the best option

2025-04-03 09:10 UTC, CommanderStorm commented
I'm prefer to not revert to plain text.
Let's stick with the current solution if then only android is affected. Seems like the lowest of all 3

2025-04-04 06:59 UTC, Erikel746 commented
Maybe google will fix the bug at some point. Then it should work as intended

2025-04-15 09:07 UTC, Mazvy commented
I see this as a regression. Opened a new issue for this https://github.com/louislam/uptime-kuma/issues/5776