ansible role added
louislam/uptime-kuma pull request #662
Opened 2021-10-11 20:24 UTC by mhkarimi1383

using ansible you can automate installation process and make it cleaner and faster  
this playbook will install docker
then install uptime kuma using docker
and install and configure nginx with ssl

2021-10-19 13:11 UTC, louislam commented
> Any progress You will accept it or not?

It could be accept with following constraints:

- It will be added in a secondary branch as a unofficial installation method. It will also be added to the wiki too.
  Similar to Kubernetes: https://github.com/louislam/uptime-kuma/tree/k8s-unofficial/kubernetes
- It needs one more reviewer to test and to confirm the ansible script.

2021-10-19 13:15 UTC, mhkarimi1383 commented
> > Any progress You will accept it or not?
> 
> It could be accept with following constraints:
> 
> * It will be added in a secondary branch as a unofficial installation method. It will also be added to the wiki too.
>   Similar to Kubernetes: https://github.com/louislam/uptime-kuma/tree/k8s-unofficial/kubernetes
> * It needs one more reviewer to test and to confirm the ansible script.

Thanks
I think should wait for another user I think to approve it.

2021-10-30 16:57 UTC, louislam commented
> I should still wait?

An extra tester is still needed.

2021-10-30 16:59 UTC, gaby commented
I don't think this role should install Docker, Docker-Compose, etc on a host. There's plenty of official roles for doing that kind of stuff, no need to reinvent the wheel. This role should ONLY cover `Uptime-Kuma` provisioning.

2021-10-30 17:12 UTC, gaby requested changes

2021-10-30 17:12 UTC, gaby commented on ansible/roles/uptime-kuma/templates/docker-compose.yml
> +        image: 'louislam/uptime-kuma:alpine'
Still valid comment

2021-10-30 17:12 UTC, gaby commented on ansible/roles/nginx/templates/docker-compose.yml
> +        network_mode: host
This shouldn't be using HOST network. Use port-binding to port 80 and 443

2021-10-30 17:12 UTC, gaby commented on ansible/roles/uptime-kuma/templates/docker-compose.yml
> +            - '127.0.0.1:3001:3001'
There's not need to use `ports` here, only NGINX should be binding ports to the host. Instead use `expose`, which only exposes the port to the Docker network.

```
expose:
  - 3001
```

2021-10-30 17:12 UTC, gaby commented on ansible/roles/nginx/templates/nginx.conf
> +            proxy_pass         http://localhost:3001/;
This should be: 

```
proxy_pass	http://uptime-kuma:3001;
```

Since the service gets a hostname assigned by Docker Network.

2021-10-30 17:12 UTC, gaby commented on ansible/roles/nginx/templates/docker-compose.yml
> +    nginx:
Why is NGINX by itself on a separate Docker-Compose file?

The current NGINX is only reverse-proxying Uptime-Kuma, so they should be both on the same file that way you don't have to manage multiple Docker Networks.

2021-10-30 17:12 UTC, gaby commented on ansible/roles/nginx/templates/nginx.conf
> +        access_log      /var/log/nginx/yoursite.access.log main;
Suggest creating a folder: 

`/var/log/nginx/uptime-kuma`

Which will container 

```
access.log
error.log

```

2021-10-30 17:12 UTC, gaby commented on ansible/roles/uptime-kuma/templates/docker-compose.yml
> +    uptime-kuma:
This whole compose file should be merge with the NGINX one. No need to run 2 compose instances if NGINX is only managing traffic for `uptime-kuma`

2021-10-30 17:12 UTC, gaby commented on ansible/playbook.yml
> +    docker_compose_version: "v2.0.1"
docker-compose 2.0.1 is not installable via PIP. They migrated from Python to Golang for v2.x.x

2021-10-30 17:14 UTC, gaby commented
@louislam @mhkarimi1383 Added comment.

2021-10-30 17:22 UTC, gaby commented
@mhkarimi1383 

Example docker-compose.yml

```
version: '3'

services:
    nginx:
        image: nginx:stable
        container_name: nginx
        restart: always
        networks:
			- uptime-kuma
        ports:
            - 443:443
            - 80:80
        volumes:
            - /compose/volumes/nginx/:/etc/nginx/
            
    uptime-kuma:
        image: louislam/uptime-kuma:1-debian
        container_name: uptime-kuma
        restart: always
        networks:
			- uptime-kuma
        expose:
        	- 3001
        volumes:
            - /compose/volumes/uptime-kuma:/app/data

networks:
  uptime-kuma: 
```

2021-11-03 20:32 UTC, mhkarimi1383 commented
I will add your suggestions...
 thanks

2021-11-03 20:37 UTC, mhkarimi1383 commented
but for docker tag I'm not sure.....

2021-11-08 17:37 UTC, mhkarimi1383 commented
@gaby You suggestions Are applied with some improvements

2021-11-19 05:09 UTC, gaby approved these changes

2021-11-19 05:09 UTC, gaby commented
👍🏻 Looks good to me

2021-12-01 19:00 UTC, mhkarimi1383 commented
Still waiting :)

2021-12-10 08:33 UTC, mhkarimi1383 commented
I'm waiting for this merge :)

2021-12-14 10:53 UTC, louislam commented
Have been merged into `ansible-unofficial` branch:
https://github.com/louislam/uptime-kuma/tree/ansible-unofficial/ansible

Also added in "How to Install":
https://github.com/louislam/uptime-kuma/wiki/%F0%9F%94%A7-How-to-Install

Thank you so much.
Feel free to make a new pull request to `ansible-unofficial` branch if you need to update the ansible config in the future.

2021-12-14 10:53 UTC, closed without merging

2021-12-14 16:52 UTC, mhkarimi1383 commented
Thanks :)